[package]
name = "blueos-recorder-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blueos-domain.workspace = true
blueos-recorder-capture = { path = "../capture" }
blueos-recorder-library.workspace = true
blueos-recorder-paths.workspace = true

[lints]
workspace = true

[dev-dependencies]
