# podman-restart only starts the "always" policy, but the BlueOS version chooser creates the bootstrap with "unless-stopped"
[Unit]
Requires=podman.socket
After=podman.socket

[Service]
ExecStart=
ExecStart=/usr/bin/podman $LOGGING start --all --filter restart-policy=always --filter restart-policy=unless-stopped
