// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit: change
// the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

import type * as Idl from '@blueos-idl/messages'

import {
  commandKey,
  queryKey,
  stateKey,
} from '../keys'

/** The name of the `example` Service, in each of its keys: `blueos/v1/example/...`. */
export const NAME = 'example'

/** job `SetLevel` at `blueos/v1/example/command/SetLevel`. */
export const SetLevel = {
  kind: 'job' as const,
  name: 'SetLevel',
  key: commandKey(NAME, 'SetLevel'),
  type: 'blueos_example_msgs/action/SetLevel' as const,
  goalSchema: 'blueos_example_msgs/action/SetLevel_Goal' as const,
  feedbackSchema: 'blueos_example_msgs/action/SetLevel_Feedback' as const,
  resultSchema: 'blueos_example_msgs/action/SetLevel_Result' as const,
}
export type SetLevelGoal = Idl.SetLevelGoal
export type SetLevelFeedback = Idl.SetLevelFeedback
export type SetLevelResult = Idl.SetLevelResult

/** query `Level` at `blueos/v1/example/query/Level`. */
export const Level = {
  kind: 'query' as const,
  name: 'Level',
  key: queryKey(NAME, 'Level'),
  type: 'blueos_example_msgs/srv/Level' as const,
  requestSchema: 'blueos_example_msgs/srv/Level_Request' as const,
  responseSchema: 'blueos_example_msgs/srv/Level_Response' as const,
}
export type LevelRequest = Idl.LevelRequest
export type LevelResponse = Idl.LevelResponse

/** state `pump` at `blueos/v1/example/state/pump`. */
export const pump = {
  kind: 'state' as const,
  name: 'pump',
  key: stateKey(NAME, 'pump'),
  type: 'blueos_example_msgs/msg/PumpState' as const,
  messageSchema: 'blueos_example_msgs/msg/PumpState' as const,
}
export type Pump = Idl.PumpState
