// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit: change
// the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

import type * as Idl from '@blueos-idl/messages'

import {
  commandKey,
  queryKey,
  stateKey,
} from '../keys'

/** The name of the `example` Service, in each of its keys: `blueos/v1/example/...`. */
export const NAME = 'example'

/** command `SetLevel` at `blueos/v1/example/command/SetLevel`. */
export const SetLevel = {
  kind: 'command' as const,
  name: 'SetLevel',
  key: commandKey(NAME, 'SetLevel'),
  requestSchema: 'blueos_example_msgs/msg/SetLevelRequest' as const,
}
export type SetLevelRequest = Idl.SetLevelRequest

/** query `Level` at `blueos/v1/example/query/Level`. */
export const Level = {
  kind: 'query' as const,
  name: 'Level',
  key: queryKey(NAME, 'Level'),
  requestSchema: 'blueos_example_msgs/msg/EmptyRequest' as const,
  responseSchema: 'blueos_example_msgs/msg/LevelQueryResponse' as const,
}
export type LevelRequest = Idl.EmptyRequest
export type LevelResponse = Idl.LevelQueryResponse

/** state `pump` at `blueos/v1/example/state/pump`. */
export const pump = {
  kind: 'state' as const,
  name: 'pump',
  key: stateKey(NAME, 'pump'),
  messageSchema: 'blueos_example_msgs/msg/PumpState' as const,
}
export type Pump = Idl.PumpState
