// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit: change
// the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

import type * as Idl from '@blueos-idl/messages'

import {
  commandKey,
  eventKey,
  queryKey,
  stateKey,
} from '../keys'

/** The name of the `recorder` Service, in each of its keys: `blueos/v1/recorder/...`. */
export const NAME = 'recorder'

/** command `DeleteRecording` at `blueos/v1/recorder/command/DeleteRecording`. */
export const DeleteRecording = {
  kind: 'command' as const,
  name: 'DeleteRecording',
  key: commandKey(NAME, 'DeleteRecording'),
  requestSchema: 'blueos_recorder_msgs/msg/DeleteRecordingCommand' as const,
}
export type DeleteRecordingRequest = Idl.DeleteRecordingCommand

/** command `RepairRecording` at `blueos/v1/recorder/command/RepairRecording`. */
export const RepairRecording = {
  kind: 'command' as const,
  name: 'RepairRecording',
  key: commandKey(NAME, 'RepairRecording'),
  requestSchema: 'blueos_recorder_msgs/msg/RepairRecordingCommand' as const,
}
export type RepairRecordingRequest = Idl.RepairRecordingCommand

/** command `SnapshotRecording` at `blueos/v1/recorder/command/SnapshotRecording`. */
export const SnapshotRecording = {
  kind: 'command' as const,
  name: 'SnapshotRecording',
  key: commandKey(NAME, 'SnapshotRecording'),
  requestSchema: 'blueos_recorder_msgs/msg/SnapshotRecordingCommand' as const,
}
export type SnapshotRecordingRequest = Idl.SnapshotRecordingCommand

/** command `Start` at `blueos/v1/recorder/command/Start`. */
export const Start = {
  kind: 'command' as const,
  name: 'Start',
  key: commandKey(NAME, 'Start'),
  requestSchema: 'blueos_recorder_msgs/msg/StartRecordingCommand' as const,
}
export type StartRequest = Idl.StartRecordingCommand

/** command `Stop` at `blueos/v1/recorder/command/Stop`. */
export const Stop = {
  kind: 'command' as const,
  name: 'Stop',
  key: commandKey(NAME, 'Stop'),
  requestSchema: 'blueos_recorder_msgs/msg/StopRecordingCommand' as const,
}
export type StopRequest = Idl.StopRecordingCommand

/** io_query `index` at `blueos/v1/recorder/query/index`. */
export const index = {
  kind: 'io_query' as const,
  name: 'index',
  key: queryKey(NAME, 'index'),
  requestSchema: 'blueos_recorder_msgs/msg/RecordingIndexRequest' as const,
  responseSchema: 'blueos_recorder_msgs/msg/RecordingIndex' as const,
}
export type indexRequest = Idl.RecordingIndexRequest
export type indexResponse = Idl.RecordingIndex

/** state `library` at `blueos/v1/recorder/state/library`. */
export const library = {
  kind: 'state' as const,
  name: 'library',
  key: stateKey(NAME, 'library'),
  messageSchema: 'blueos_recorder_msgs/msg/RecordingLibrary' as const,
}
export type Library = Idl.RecordingLibrary

/** state `recording` at `blueos/v1/recorder/state/recording`. */
export const recording = {
  kind: 'state' as const,
  name: 'recording',
  key: stateKey(NAME, 'recording'),
  messageSchema: 'blueos_recorder_msgs/msg/RecordingState' as const,
}
export type Recording = Idl.RecordingState

/** event `operation` at `blueos/v1/recorder/event/operation`. */
export const operation = {
  kind: 'event' as const,
  name: 'operation',
  key: eventKey(NAME, 'operation'),
  messageSchema: 'blueos_recorder_msgs/msg/RecordingOperation' as const,
}
export type Operation = Idl.RecordingOperation
