// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit: change
// the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

import type * as Idl from '@blueos-idl/messages'

import {
  commandKey,
  queryKey,
  stateKey,
} from '../keys'

/** The name of the `recorder` Service, in each of its keys: `blueos/v1/recorder/...`. */
export const NAME = 'recorder'

/** job `DeleteRecording` at `blueos/v1/recorder/command/DeleteRecording`. */
export const DeleteRecording = {
  kind: 'job' as const,
  name: 'DeleteRecording',
  key: commandKey(NAME, 'DeleteRecording'),
  type: 'blueos_recorder_msgs/action/DeleteRecording' as const,
  goalSchema: 'blueos_recorder_msgs/action/DeleteRecording_Goal' as const,
  feedbackSchema: 'blueos_recorder_msgs/action/DeleteRecording_Feedback' as const,
  resultSchema: 'blueos_recorder_msgs/action/DeleteRecording_Result' as const,
}
export type DeleteRecordingGoal = Idl.DeleteRecordingGoal
export type DeleteRecordingFeedback = Idl.DeleteRecordingFeedback
export type DeleteRecordingResult = Idl.DeleteRecordingResult

/** job `RepairRecording` at `blueos/v1/recorder/command/RepairRecording`. */
export const RepairRecording = {
  kind: 'job' as const,
  name: 'RepairRecording',
  key: commandKey(NAME, 'RepairRecording'),
  type: 'blueos_recorder_msgs/action/RepairRecording' as const,
  goalSchema: 'blueos_recorder_msgs/action/RepairRecording_Goal' as const,
  feedbackSchema: 'blueos_recorder_msgs/action/RepairRecording_Feedback' as const,
  resultSchema: 'blueos_recorder_msgs/action/RepairRecording_Result' as const,
}
export type RepairRecordingGoal = Idl.RepairRecordingGoal
export type RepairRecordingFeedback = Idl.RepairRecordingFeedback
export type RepairRecordingResult = Idl.RepairRecordingResult

/** job `SnapshotRecording` at `blueos/v1/recorder/command/SnapshotRecording`. */
export const SnapshotRecording = {
  kind: 'job' as const,
  name: 'SnapshotRecording',
  key: commandKey(NAME, 'SnapshotRecording'),
  type: 'blueos_recorder_msgs/action/SnapshotRecording' as const,
  goalSchema: 'blueos_recorder_msgs/action/SnapshotRecording_Goal' as const,
  feedbackSchema: 'blueos_recorder_msgs/action/SnapshotRecording_Feedback' as const,
  resultSchema: 'blueos_recorder_msgs/action/SnapshotRecording_Result' as const,
}
export type SnapshotRecordingGoal = Idl.SnapshotRecordingGoal
export type SnapshotRecordingFeedback = Idl.SnapshotRecordingFeedback
export type SnapshotRecordingResult = Idl.SnapshotRecordingResult

/** job `Start` at `blueos/v1/recorder/command/Start`. */
export const Start = {
  kind: 'job' as const,
  name: 'Start',
  key: commandKey(NAME, 'Start'),
  type: 'blueos_recorder_msgs/action/StartRecording' as const,
  goalSchema: 'blueos_recorder_msgs/action/StartRecording_Goal' as const,
  feedbackSchema: 'blueos_recorder_msgs/action/StartRecording_Feedback' as const,
  resultSchema: 'blueos_recorder_msgs/action/StartRecording_Result' as const,
}
export type StartGoal = Idl.StartRecordingGoal
export type StartFeedback = Idl.StartRecordingFeedback
export type StartResult = Idl.StartRecordingResult

/** job `Stop` at `blueos/v1/recorder/command/Stop`. */
export const Stop = {
  kind: 'job' as const,
  name: 'Stop',
  key: commandKey(NAME, 'Stop'),
  type: 'blueos_recorder_msgs/action/StopRecording' as const,
  goalSchema: 'blueos_recorder_msgs/action/StopRecording_Goal' as const,
  feedbackSchema: 'blueos_recorder_msgs/action/StopRecording_Feedback' as const,
  resultSchema: 'blueos_recorder_msgs/action/StopRecording_Result' as const,
}
export type StopGoal = Idl.StopRecordingGoal
export type StopFeedback = Idl.StopRecordingFeedback
export type StopResult = Idl.StopRecordingResult

/** query `bytes` at `blueos/v1/recorder/query/bytes`. */
export const bytes = {
  kind: 'query' as const,
  name: 'bytes',
  key: queryKey(NAME, 'bytes'),
  type: 'blueos_recorder_msgs/srv/RecordingBytes' as const,
  requestSchema: 'blueos_recorder_msgs/srv/RecordingBytes_Request' as const,
  responseSchema: 'blueos_recorder_msgs/srv/RecordingBytes_Response' as const,
}
export type bytesRequest = Idl.RecordingBytesRequest
export type bytesResponse = Idl.RecordingBytesResponse

/** query `index` at `blueos/v1/recorder/query/index`. */
export const index = {
  kind: 'query' as const,
  name: 'index',
  key: queryKey(NAME, 'index'),
  type: 'blueos_recorder_msgs/srv/RecordingIndex' as const,
  requestSchema: 'blueos_recorder_msgs/srv/RecordingIndex_Request' as const,
  responseSchema: 'blueos_recorder_msgs/srv/RecordingIndex_Response' as const,
}
export type indexRequest = Idl.RecordingIndexRequest
export type indexResponse = Idl.RecordingIndexResponse

/** state `library` at `blueos/v1/recorder/state/library`. */
export const library = {
  kind: 'state' as const,
  name: 'library',
  key: stateKey(NAME, 'library'),
  type: 'blueos_recorder_msgs/msg/RecordingLibrary' as const,
  messageSchema: 'blueos_recorder_msgs/msg/RecordingLibrary' as const,
}
export type Library = Idl.RecordingLibrary

/** state `recording` at `blueos/v1/recorder/state/recording`. */
export const recording = {
  kind: 'state' as const,
  name: 'recording',
  key: stateKey(NAME, 'recording'),
  type: 'blueos_recorder_msgs/msg/RecordingState' as const,
  messageSchema: 'blueos_recorder_msgs/msg/RecordingState' as const,
}
export type Recording = Idl.RecordingState
