// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit: change
// the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

import type * as Idl from '@blueos-idl/messages'

import {
  commandKey,
  eventKey,
  queryKey,
  stateKey,
} from '../keys'

/** The name of the `tank` Service, in each of its keys: `blueos/v1/tank/...`. */
export const NAME = 'tank'

/** command `Drain` at `blueos/v1/tank/command/Drain`. */
export const Drain = {
  kind: 'command' as const,
  name: 'Drain',
  key: commandKey(NAME, 'Drain'),
  requestSchema: 'blueos_example_msgs/msg/EmptyRequest' as const,
}
export type DrainRequest = Idl.EmptyRequest

/** command `SetLevel` at `blueos/v1/tank/command/SetLevel`. */
export const SetLevel = {
  kind: 'command' as const,
  name: 'SetLevel',
  key: commandKey(NAME, 'SetLevel'),
  requestSchema: 'blueos_example_msgs/msg/SetLevelRequest' as const,
}
export type SetLevelRequest = Idl.SetLevelRequest

/** query `Level` at `blueos/v1/tank/query/Level`. */
export const Level = {
  kind: 'query' as const,
  name: 'Level',
  key: queryKey(NAME, 'Level'),
  requestSchema: 'blueos_example_msgs/msg/EmptyRequest' as const,
  responseSchema: 'blueos_example_msgs/msg/LevelQueryResponse' as const,
}
export type LevelRequest = Idl.EmptyRequest
export type LevelResponse = Idl.LevelQueryResponse

/** query `LevelAfterFill` at `blueos/v1/tank/query/LevelAfterFill`. */
export const LevelAfterFill = {
  kind: 'query' as const,
  name: 'LevelAfterFill',
  key: queryKey(NAME, 'LevelAfterFill'),
  requestSchema: 'blueos_example_msgs/msg/SetLevelRequest' as const,
  responseSchema: 'blueos_example_msgs/msg/LevelQueryResponse' as const,
}
export type LevelAfterFillRequest = Idl.SetLevelRequest
export type LevelAfterFillResponse = Idl.LevelQueryResponse

/** io_query `Probe` at `blueos/v1/tank/query/Probe`. */
export const Probe = {
  kind: 'io_query' as const,
  name: 'Probe',
  key: queryKey(NAME, 'Probe'),
  requestSchema: 'blueos_example_msgs/msg/EmptyRequest' as const,
  responseSchema: 'blueos_example_msgs/msg/LevelQueryResponse' as const,
}
export type ProbeRequest = Idl.EmptyRequest
export type ProbeResponse = Idl.LevelQueryResponse

/** state `tank` at `blueos/v1/tank/state/tank`. */
export const tank = {
  kind: 'state' as const,
  name: 'tank',
  key: stateKey(NAME, 'tank'),
  messageSchema: 'blueos_example_msgs/msg/LevelQueryResponse' as const,
}
export type Tank = Idl.LevelQueryResponse

/** event `Emptied` at `blueos/v1/tank/event/Emptied`. */
export const Emptied = {
  kind: 'event' as const,
  name: 'Emptied',
  key: eventKey(NAME, 'Emptied'),
  messageSchema: 'blueos_example_msgs/msg/EmptyRequest' as const,
}
export type Emptied = Idl.EmptyRequest

/** event `LevelChanged` at `blueos/v1/tank/event/LevelChanged`. */
export const LevelChanged = {
  kind: 'event' as const,
  name: 'LevelChanged',
  key: eventKey(NAME, 'LevelChanged'),
  messageSchema: 'blueos_example_msgs/msg/LevelQueryResponse' as const,
}
export type LevelChanged = Idl.LevelQueryResponse
