[package]
name = "blueos-tank-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blueos-domain.workspace = true
blueos-idl.workspace = true
blueos-service.workspace = true
blueos-tank-api.workspace = true
blueos-tank-domain.workspace = true
clap = { workspace = true, features = ["derive", "std"] }

[dev-dependencies]
blueos-api.workspace = true
blueos-comms.workspace = true
blueos-service = { workspace = true, features = ["testing"] }
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time"] }

[lints]
workspace = true
