//! The conversions between the Messages and the Domain of the `recorder` Service, one function per endpoint.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use blueos_domain::Domain;
use blueos_idl::msg::blueos_recorder_msgs;

/// Converts between the Domain and the Messages of every endpoint of the `recorder` Service that is not
/// `custom`. Implement it for the Domain in this crate: `register` in the app crate calls it.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not convert the endpoints of the `recorder` Service",
    label = "no `impl Conversions for {Self}` in the `recorder` logic/api crate",
    note = "implement `start` for the Command `Start`, `stop` for the Command `Stop`, `library` for the State `library`, `recording` for the State `recording`, `operation` for the Event `operation`"
)]
pub trait Conversions: Domain {
    /// The Command `Start`, at `blueos/v1/recorder/command/Start`.
    ///
    /// The Domain's Request for the Message.
    fn start(request: blueos_recorder_msgs::StartRecordingCommand) -> Self::Request;

    /// The Command `Stop`, at `blueos/v1/recorder/command/Stop`.
    ///
    /// The Domain's Request for the Message.
    fn stop(request: blueos_recorder_msgs::StopRecordingCommand) -> Self::Request;

    /// The State `library`, at `blueos/v1/recorder/state/library`.
    ///
    /// Its value for `snapshot`.
    fn library(snapshot: &Self::Snapshot) -> blueos_recorder_msgs::RecordingLibrary;

    /// The State `recording`, at `blueos/v1/recorder/state/recording`.
    ///
    /// Its value for `snapshot`.
    fn recording(snapshot: &Self::Snapshot) -> blueos_recorder_msgs::RecordingState;

    /// The Event `operation`, at `blueos/v1/recorder/event/operation`.
    ///
    /// What it publishes for `event`, or `None` when `event` is another one.
    fn operation(event: &Self::Event) -> Option<blueos_recorder_msgs::RecordingOperation>;
}
