pub mod catalog;
pub mod criticality;
pub mod drift;
pub mod edge;
pub mod export;
pub mod id;
pub mod interface;
pub mod lifecycle;
pub mod observed;
pub mod provenance;
pub mod resolve;
pub mod resource;
pub mod service;
pub mod services;
pub mod state;
pub mod trust;
pub mod validate;

pub use catalog::{Catalog, CouplingMatrix};
pub use criticality::CriticalityTier;
pub use drift::{diff, diff_catalog, DriftFinding, DriftReport};
pub use edge::{Bus, Edge, FailureImpact, SyncMode};
pub use export::{export_json, export_mermaid, export_schema};
pub use id::{CapabilityId, PathRef, Port, PortRef, ServiceId};
pub use interface::{FileAccessMode, Interface, MavlinkRole};
pub use lifecycle::{Lifecycle, ObservedLifecycle};
pub use observed::{ObservedFacts, ResourceLimits, ServiceKind, StartupTier};
pub use provenance::{Asserted, Evidence, Observed};
pub use resolve::{resolve, resolve_port_ref, resolve_service_ports, ResolveError, ResolvedPorts};
pub use resource::{Resource, ResourceOwnership};
pub use service::{Authority, ServiceDefinition};
pub use state::StateMachine;
pub use trust::{DangerousOperation, PrivilegeLevel, UserConfirmation};
pub use validate::{validate, ValidationError, COVERAGE_UNKNOWN_THRESHOLD};
