[package]
name = "blueos"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "blueos"
path = "src/main.rs"

[features]
example = ["dep:blueos-example-app"]
probe = ["blueos-service/probe"]
recorder = ["blueos-recorder-app"]

[dependencies]
blueos-example-app = { workspace = true, optional = true }
blueos-recorder-app = { workspace = true, optional = true }
blueos-service.workspace = true

[lints]
workspace = true
