[package]
name = "blueos"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "blueos"
path = "src/main.rs"

[features]
default = []
example = ["dep:blueos-example"]
recorder = ["dep:blueos-recorder"]

[dependencies]
blueos-example = { workspace = true, optional = true }
blueos-recorder = { workspace = true, optional = true }
