//! The endpoints of the `tank` Service, registered as `endpoints.toml` lists them.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use core::future::Future;
use std::sync::Arc;

use blueos_domain::DomainQueries;
use blueos_idl::msg::blueos_example_msgs;
use blueos_service::{Refusal, ServiceBuilder};
use blueos_tank_api::endpoints::Conversions;

/// The name of the `tank` Service, in each of its keys: `blueos/v1/tank/...`.
pub const NAME: &str = "tank";

/// Handles the endpoints of the `tank` Service whose mapping is not a plain conversion: the `custom`
/// Commands and Queries, and the IO queries. Implement it in `handlers.rs` and pass it to [`register`].
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not handle the custom endpoints of the `tank` Service",
    label = "no `impl Handlers<D> for {Self}` in the `tank` app crate",
    note = "implement `set_level` for the Command `SetLevel`, `level_after_fill` for the Query `LevelAfterFill`, `probe` for the IO query `Probe`"
)]
pub trait Handlers<D: DomainQueries>: Send + Sync + 'static {
    /// The Command `SetLevel`, at `blueos/v1/tank/command/SetLevel`.
    ///
    /// The Domain's Request for the Message, or why it is refused.
    fn set_level(
        &self,
        request: blueos_example_msgs::SetLevelRequest,
    ) -> Result<D::Request, Refusal>;

    /// The Query `LevelAfterFill`, at `blueos/v1/tank/query/LevelAfterFill`.
    ///
    /// The Domain's Query for the Message, or why it is refused.
    fn level_after_fill(
        &self,
        request: blueos_example_msgs::SetLevelRequest,
    ) -> Result<D::Query, Refusal>;

    /// The IO query `Probe`, at `blueos/v1/tank/query/Probe`.
    ///
    /// Its reply, read outside the Inbox, or why it is refused.
    fn probe(
        &self,
        request: blueos_example_msgs::EmptyRequest,
    ) -> impl Future<Output = Result<blueos_example_msgs::LevelQueryResponse, Refusal>> + Send;
}

/// Registers every endpoint of `endpoints.toml` on `builder`, with `handlers` for the custom ones.
pub fn register<D: Conversions, H: Handlers<D>, Context>(
    builder: ServiceBuilder<D, Context>,
    handlers: H,
) -> ServiceBuilder<D, Context> {
    let handlers = Arc::new(handlers);
    builder
        .command("Drain", |request: blueos_example_msgs::EmptyRequest| {
            Ok(<D as Conversions>::drain(request))
        })
        .command("SetLevel", {
            let handlers = Arc::clone(&handlers);
            move |request: blueos_example_msgs::SetLevelRequest| H::set_level(&handlers, request)
        })
        .query(
            "Level",
            |request: blueos_example_msgs::EmptyRequest| Ok(<D as Conversions>::level(request)),
            <D as Conversions>::level_response,
        )
        .query(
            "LevelAfterFill",
            {
                let handlers = Arc::clone(&handlers);
                move |request: blueos_example_msgs::SetLevelRequest| {
                    H::level_after_fill(&handlers, request)
                }
            },
            <D as Conversions>::level_after_fill_response,
        )
        .io_query("Probe", {
            let handlers = Arc::clone(&handlers);
            move |request: blueos_example_msgs::EmptyRequest| {
                let handlers = Arc::clone(&handlers);
                Box::pin(async move { H::probe(&handlers, request).await })
            }
        })
        .state("tank", <D as Conversions>::tank)
        .event("Emptied", <D as Conversions>::emptied)
        .event("LevelChanged", <D as Conversions>::level_changed)
        .manifest_endpoints(vec![
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "Drain".into(),
                key: "blueos/v1/tank/command/Drain".into(),
                request_schema: "blueos_example_msgs/msg/EmptyRequest".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "SetLevel".into(),
                key: "blueos/v1/tank/command/SetLevel".into(),
                request_schema: "blueos_example_msgs/msg/SetLevelRequest".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "query".into(),
                name: "Level".into(),
                key: "blueos/v1/tank/query/Level".into(),
                request_schema: "blueos_example_msgs/msg/EmptyRequest".into(),
                response_schema: "blueos_example_msgs/msg/LevelQueryResponse".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "query".into(),
                name: "LevelAfterFill".into(),
                key: "blueos/v1/tank/query/LevelAfterFill".into(),
                request_schema: "blueos_example_msgs/msg/SetLevelRequest".into(),
                response_schema: "blueos_example_msgs/msg/LevelQueryResponse".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "io_query".into(),
                name: "Probe".into(),
                key: "blueos/v1/tank/query/Probe".into(),
                request_schema: "blueos_example_msgs/msg/EmptyRequest".into(),
                response_schema: "blueos_example_msgs/msg/LevelQueryResponse".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "tank".into(),
                key: "blueos/v1/tank/state/tank".into(),
                request_schema: "".into(),
                response_schema: "blueos_example_msgs/msg/LevelQueryResponse".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "event".into(),
                name: "Emptied".into(),
                key: "blueos/v1/tank/event/Emptied".into(),
                request_schema: "".into(),
                response_schema: "blueos_example_msgs/msg/EmptyRequest".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "event".into(),
                name: "LevelChanged".into(),
                key: "blueos/v1/tank/event/LevelChanged".into(),
                request_schema: "".into(),
                response_schema: "blueos_example_msgs/msg/LevelQueryResponse".into(),
            },
        ])
}
