//! Generates each Service's endpoint registration from its endpoint manifest (D-26).
//!
//! A Service's app crate commits `endpoints.toml`, next to its `Cargo.toml`. It lists four kinds of endpoint, `job`,
//! `query`, `state` and `event`, each with its interface type in `type`. From it the generator writes two committed
//! files: `logic/api/src/endpoints.rs`, the `Conversions` trait its Domain implements, and `app/src/endpoints.rs`,
//! the Service `NAME`, the `Handlers` trait of the `custom` Job types and `io` Queries, and `register`.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs, io,
    io::Write as _,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use convert_case::{Case, Casing};
use serde::Deserialize;

/// The file name of an endpoint manifest, next to the `Cargo.toml` of a Service's app crate.
pub const MANIFEST_FILE: &str = "endpoints.toml";

/// Where the TypeScript clients are committed, under `core/`.
const TYPESCRIPT_DIR: &str = "frontend/src/libs/blueos-api/services";

/// The endpoints D-12 gives every Service. A manifest cannot reuse their names, and `api.lock` records them for
/// every Service.
// ponytail: records `settings` and `UpdateSettings` for every Service, as the generator cannot see a
// `ServiceBuilder::settings` opt-in; a manifest field would make the lock exact.
// A Job control names its Job in the attachment, so a body is needed only to answer a permission request.
const STANDARD_ENDPOINTS: [StandardEndpoint; 11] = [
    StandardEndpoint {
        name: "info",
        key: "query/info",
        interface_type: "blueos_msgs/msg/ServiceInfo",
    },
    StandardEndpoint {
        name: "status",
        key: "state/status",
        interface_type: "blueos_msgs/msg/ServiceStatus",
    },
    StandardEndpoint {
        name: "settings",
        key: "settings",
        interface_type: "blueos_msgs/msg/SettingsEnvelope",
    },
    StandardEndpoint {
        name: "UpdateSettings",
        key: "command/UpdateSettings",
        interface_type: "blueos_msgs/action/UpdateSettings",
    },
    StandardEndpoint {
        name: "log",
        key: "log",
        interface_type: "foxglove_msgs/msg/Log",
    },
    StandardEndpoint {
        name: "metrics",
        key: "state/metrics",
        interface_type: "blueos_msgs/msg/ServiceMetrics",
    },
    StandardEndpoint {
        name: "jobs",
        key: "jobs",
        interface_type: "blueos_msgs/msg/JobList",
    },
    StandardEndpoint {
        name: "CancelJob",
        key: "command/CancelJob",
        interface_type: "std_msgs/msg/Empty",
    },
    StandardEndpoint {
        name: "PauseJob",
        key: "command/PauseJob",
        interface_type: "std_msgs/msg/Empty",
    },
    StandardEndpoint {
        name: "ResumeJob",
        key: "command/ResumeJob",
        interface_type: "std_msgs/msg/Empty",
    },
    StandardEndpoint {
        name: "AnswerPermission",
        key: "command/AnswerPermission",
        interface_type: "blueos_msgs/msg/PermissionAnswer",
    },
];

const GENERATED_NOTICE: &str = "//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not \
                                edit it: change\n//! the manifest and run `cargo run -p blueos-idl-codegen -- \
                                --write` in `core/`.\n";

const TYPESCRIPT_GENERATED_NOTICE: &str = "// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. \
                                          Do not edit: change\n// the manifest and run `cargo run -p blueos-idl-codegen \
                                          -- --write` in `core/`.\n";

/// Why the generator could not generate the endpoint files of the workspace.
#[derive(Debug, thiserror::Error)]
pub enum EndpointsError {
    /// A file could not be read.
    #[error("{}: {error}", path.display())]
    Read {
        /// The file.
        path: PathBuf,
        /// Why it could not be read.
        error: io::Error,
    },
    /// A `Cargo.toml` does not parse, or misses the field the generator needs.
    #[error("{}: {reason}", path.display())]
    Cargo {
        /// The `Cargo.toml`.
        path: PathBuf,
        /// What is wrong with it.
        reason: String,
    },
    /// An endpoint manifest is wrong.
    #[error("{}: {error}", path.display())]
    Manifest {
        /// The manifest.
        path: PathBuf,
        /// What is wrong with it.
        error: ManifestError,
    },
}

/// What is wrong with an endpoint manifest.
#[derive(Debug, PartialEq, Eq, thiserror::Error)]
pub enum ManifestError {
    /// The manifest is not valid TOML, or has a field the format does not have.
    #[error("the manifest does not parse: {0}")]
    Parse(String),
    /// A Service or endpoint name is not a plain identifier.
    #[error(
        "`{0}` is not a valid name: use ASCII letters, digits and `_`, start with a letter, and avoid Rust keywords"
    )]
    InvalidName(String),
    /// An endpoint uses a name every Service already has (D-12).
    #[error("the endpoint `{0}` uses a name every Service already has (D-12)")]
    Reserved(String),
    /// Two endpoints generate the same function.
    #[error(
        "the endpoints `{first}` and `{second}` both generate `{function}`: endpoint names are unique in a Service"
    )]
    Duplicate {
        /// The endpoint listed first.
        first: String,
        /// The endpoint listed second.
        second: String,
        /// The function both generate.
        function: String,
    },
    /// An endpoint's type is not an interface of its kind in `core/libs/idl/interfaces`.
    #[error(
        "the endpoint `{endpoint}` has the type `{interface_type}`, which is not a `{expected}` of `blueos-idl`"
    )]
    UnknownType {
        /// The endpoint.
        endpoint: String,
        /// The type it gave.
        interface_type: String,
        /// The interface its kind needs: `.action` for a Job type, `.srv` for a Query, `.msg` for a State or an
        /// Event.
        expected: &'static str,
    },
}

/// A generated file and what it should contain.
#[derive(Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Where the file is committed.
    pub path: PathBuf,
    /// Its formatted text.
    pub contents: String,
}

/// The generated sources of one manifest, before formatting.
#[derive(Debug)]
pub struct Generated {
    /// The Service name from the manifest.
    pub service: String,
    /// `logic/api/src/endpoints.rs`: the `Conversions` trait.
    pub api: String,
    /// `app/src/endpoints.rs`: `NAME`, the `Handlers` trait and `register`.
    pub app: String,
    /// `frontend/src/libs/blueos-api/services/<service>.ts`: keys and Message types (D-14).
    pub typescript: String,
}

/// `endpoints.toml`. Each table maps an endpoint name to its interface type, in sorted order.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Manifest {
    service: String,
    #[serde(default)]
    job: BTreeMap<String, JobEntry>,
    #[serde(default)]
    query: BTreeMap<String, QueryEntry>,
    #[serde(default)]
    state: BTreeMap<String, PublishedEntry>,
    #[serde(default)]
    event: BTreeMap<String, PublishedEntry>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct JobEntry {
    #[serde(rename = "type")]
    interface_type: String,
    #[serde(default)]
    custom: bool,
    nature: Option<NatureEntry>,
}

/// What a Job type allows (D-36). A Job type without one is an instant Job type that allows nothing.
#[derive(Clone, Copy, Deserialize)]
#[serde(deny_unknown_fields)]
struct NatureEntry {
    #[serde(default)]
    lasting: bool,
    #[serde(default)]
    cancellable: bool,
    #[serde(default)]
    pausable: bool,
    #[serde(default)]
    needs_permission: bool,
}

/// A Query: `io = true` when an adapter answers it outside the Inbox, which implies its handler method.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct QueryEntry {
    #[serde(rename = "type")]
    interface_type: String,
    #[serde(default)]
    io: bool,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct PublishedEntry {
    #[serde(rename = "type")]
    interface_type: String,
}

/// One endpoint of the manifest, with its interface type.
struct Endpoint {
    kind: Kind,
    name: String,
    function: String,
    interface: InterfaceType,
    custom: bool,
    /// Set for a Job type that declares its nature, so its Goal mapping gets the Job id.
    nature: Option<NatureEntry>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Kind {
    Job,
    Query,
    IoQuery,
    State,
    Event,
}

/// An interface type, from its name `<package>/<form>/<Name>`, whose form is `action`, `srv` or `msg`.
struct InterfaceType {
    package: String,
    form: &'static str,
    name: String,
}

/// An endpoint the Kernel declares for a Service, at `blueos/v1/<service>/<key>`.
struct StandardEndpoint {
    name: &'static str,
    key: &'static str,
    interface_type: &'static str,
}

impl Endpoint {
    fn key(&self, service: &str) -> String {
        let segment = match self.kind {
            Kind::Job => "command",
            Kind::Query | Kind::IoQuery => "query",
            Kind::State => "state",
            Kind::Event => "event",
        };
        format!("blueos/v1/{service}/{segment}/{}", self.name)
    }

    fn title(&self) -> String {
        let kind = match self.kind {
            Kind::Job => "Job type",
            Kind::Query => "Query",
            Kind::IoQuery => "IO query",
            Kind::State => "State",
            Kind::Event => "Event",
        };
        format!("{kind} `{}`", self.name)
    }

    fn is_handled(&self) -> bool {
        self.custom || self.kind == Kind::IoQuery
    }

    /// The Job id parameter of its Goal mapping: a Job type that declares its nature hands it to the Domain.
    fn job_id_parameter(&self) -> &'static str {
        if self.nature.is_some() {
            "job_id: JobId, "
        } else {
            ""
        }
    }

    /// The functions it generates in `Conversions` and `Handlers`, which must be unique in a Service.
    fn functions(&self) -> Vec<String> {
        let function = &self.function;
        match self.kind {
            Kind::Job => vec![
                function.clone(),
                format!("{function}_feedback"),
                format!("{function}_result"),
            ],
            Kind::Query => vec![function.clone(), format!("{function}_response")],
            Kind::IoQuery | Kind::State | Kind::Event => vec![function.clone()],
        }
    }

    /// Its kind in `info`: an IO query is a Query, because clients cannot tell them apart.
    fn kind_name(&self) -> &'static str {
        match self.kind {
            Kind::Job => "job",
            Kind::Query | Kind::IoQuery => "query",
            Kind::State => "state",
            Kind::Event => "event",
        }
    }
}

impl InterfaceType {
    /// The Rust path of one of its parts: `Goal`, `Result` or `Feedback` of a `.action`, `Request` or `Response`
    /// of a `.srv`, and `""` for a `.msg`.
    fn path(&self, part: &str) -> String {
        format!("{}::{}{part}", self.package, self.name)
    }

    fn schema_name(&self) -> String {
        format!("{}/{}/{}", self.package, self.form, self.name)
    }

    /// The schema name of one of its parts, as the TypeScript codec looks it up.
    fn part_schema_name(&self, part: &str) -> String {
        if part.is_empty() {
            self.schema_name()
        } else {
            format!("{}_{part}", self.schema_name())
        }
    }

    fn typescript_type(&self, part: &str) -> String {
        format!("{}{part}", self.name)
    }
}

/// Every endpoint key of the Services in workspace manifests, with the standard ones and the Feedback, Job result
/// and history of each Job type (`UpdateSettings` included), for `api.lock`. The Feedback and the Job result are
/// locked as the messages on the wire, which carry the parts of the Job type's `.action` as bytes.
pub fn collect_endpoint_lock_lines(
    core_dir: &Path,
    messages: &BTreeSet<String>,
) -> Result<Vec<String>, EndpointsError> {
    let mut lines = Vec::new();
    for (service, endpoints) in collect_service_endpoints(core_dir, messages)? {
        for standard in &STANDARD_ENDPOINTS {
            lines.push(crate::format_lock_line(
                &format!("blueos/v1/{service}/{}", standard.key),
                1,
                &format!("type={}", standard.interface_type),
            ));
        }
        let mut job_types = vec!["UpdateSettings".to_owned()];
        for endpoint in endpoints {
            lines.push(crate::format_lock_line(
                &endpoint.key(&service),
                1,
                &format!("type={}", endpoint.interface.schema_name()),
            ));
            if endpoint.kind == Kind::Job {
                job_types.push(endpoint.name);
            }
        }
        for job_type in job_types {
            for (output, interface_type) in [
                ("feedback", "blueos_msgs/msg/JobFeedbackList"),
                ("result", "blueos_msgs/msg/JobResult"),
                ("history", "blueos_msgs/msg/JobList"),
            ] {
                lines.push(crate::format_lock_line(
                    &format!("blueos/v1/{service}/jobs/{job_type}/{output}"),
                    1,
                    &format!("type={interface_type}"),
                ));
            }
        }
    }
    lines.sort();
    Ok(lines)
}

fn collect_service_endpoints(
    core_dir: &Path,
    messages: &BTreeSet<String>,
) -> Result<Vec<(String, Vec<Endpoint>)>, EndpointsError> {
    let mut collected = Vec::new();
    for member in workspace_members(core_dir)? {
        let manifest_path = core_dir.join(member).join(MANIFEST_FILE);
        if !manifest_path.is_file() {
            continue;
        }
        let manifest = read_manifest(&manifest_path)?;
        let service = manifest.service.clone();
        let service_endpoints =
            endpoints(manifest, messages).map_err(|error| EndpointsError::Manifest {
                path: manifest_path.clone(),
                error,
            })?;
        collected.push((service, service_endpoints));
    }
    Ok(collected)
}

fn read_manifest(path: &Path) -> Result<Manifest, EndpointsError> {
    let source = fs::read_to_string(path).map_err(|error| EndpointsError::Read {
        path: path.to_owned(),
        error,
    })?;
    toml::from_str(&source).map_err(|error| EndpointsError::Manifest {
        path: path.to_owned(),
        error: ManifestError::Parse(error.to_string()),
    })
}

/// Generates the endpoint files of every Service in the workspace at `core_dir`. `messages` holds the schema name
/// of every Message of `blueos-idl`.
pub fn generate_all(
    core_dir: &Path,
    messages: &BTreeSet<String>,
) -> Result<Vec<GeneratedFile>, EndpointsError> {
    let mut files = Vec::new();
    for member in workspace_members(core_dir)? {
        let app_dir = core_dir.join(member);
        let manifest_path = app_dir.join(MANIFEST_FILE);
        if !manifest_path.exists() {
            continue;
        }
        let api_dir = app_dir.with_file_name("logic").join("api");
        let api_cargo = api_dir.join("Cargo.toml");
        let api_crate = read_toml(&api_cargo)?
            .get("package")
            .and_then(|package| package.get("name"))
            .and_then(toml::Value::as_str)
            .ok_or_else(|| EndpointsError::Cargo {
                path: api_cargo.clone(),
                reason: "no `package.name`".to_owned(),
            })?
            .replace('-', "_");
        let generated =
            generate(&read(&manifest_path)?, &api_crate, messages).map_err(|error| {
                EndpointsError::Manifest {
                    path: manifest_path.clone(),
                    error,
                }
            })?;
        let typescript_dir = core_dir.join(TYPESCRIPT_DIR);
        fs::create_dir_all(&typescript_dir).map_err(|error| EndpointsError::Read {
            path: typescript_dir.clone(),
            error,
        })?;
        let typescript_path = typescript_dir.join(format!("{}.ts", generated.service));
        for (path, source, format_rust) in [
            (api_dir.join("src/endpoints.rs"), generated.api, true),
            (app_dir.join("src/endpoints.rs"), generated.app, true),
            (typescript_path, generated.typescript, false),
        ] {
            files.push(GeneratedFile {
                path,
                contents: if format_rust { format(&source) } else { source },
            });
        }
    }
    Ok(files)
}

/// The generated endpoint files under `core_dir` that `generated` does not list: the TypeScript client or the
/// wiring of a crate whose `endpoints.toml` is gone.
pub fn stray_files(
    core_dir: &Path,
    generated: &[GeneratedFile],
) -> Result<Vec<PathBuf>, EndpointsError> {
    let clients = fs::read_dir(core_dir.join(TYPESCRIPT_DIR))
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path());
    let wiring = workspace_members(core_dir)?
        .into_iter()
        .map(|member| core_dir.join(member).join("src/endpoints.rs"));
    let mut stray = Vec::new();
    for path in clients.chain(wiring) {
        let contents = match fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(error) if error.kind() == io::ErrorKind::NotFound => continue,
            Err(error) => return Err(EndpointsError::Read { path, error }),
        };
        let is_generated =
            contents.contains(GENERATED_NOTICE) || contents.contains(TYPESCRIPT_GENERATED_NOTICE);
        if is_generated && !generated.iter().any(|file| file.path == path) {
            stray.push(path);
        }
    }
    stray.sort();
    Ok(stray)
}

/// Generates the two endpoint sources of the manifest `source`, whose `logic/api` crate is `api_crate` (in its
/// Rust spelling, with `_`).
pub fn generate(
    source: &str,
    api_crate: &str,
    messages: &BTreeSet<String>,
) -> Result<Generated, ManifestError> {
    let manifest: Manifest =
        toml::from_str(source).map_err(|error| ManifestError::Parse(error.to_string()))?;
    let service = manifest.service.clone();
    let endpoints = endpoints(manifest, messages)?;
    Ok(Generated {
        api: api_source(&service, &endpoints),
        app: app_source(&service, api_crate, &endpoints),
        typescript: typescript_client_source(&service, &endpoints),
        service,
    })
}

/// The `workspace.members` of the `Cargo.toml` at `core_dir`.
fn workspace_members(core_dir: &Path) -> Result<Vec<String>, EndpointsError> {
    let workspace = read_toml(&core_dir.join("Cargo.toml"))?;
    let members = workspace
        .get("workspace")
        .and_then(|workspace| workspace.get("members"))
        .and_then(toml::Value::as_array)
        .ok_or_else(|| EndpointsError::Cargo {
            path: core_dir.join("Cargo.toml"),
            reason: "no `workspace.members` list".to_owned(),
        })?;
    Ok(members
        .iter()
        .filter_map(toml::Value::as_str)
        .map(str::to_owned)
        .collect())
}

fn read_toml(path: &Path) -> Result<toml::Table, EndpointsError> {
    read(path)?
        .parse()
        .map_err(|error: toml::de::Error| EndpointsError::Cargo {
            path: path.to_path_buf(),
            reason: error.to_string(),
        })
}

fn read(path: &Path) -> Result<String, EndpointsError> {
    fs::read_to_string(path).map_err(|error| EndpointsError::Read {
        path: path.to_path_buf(),
        error,
    })
}

/// Formats a generated source with `rustfmt`, as `cargo fmt` would. The source always parses, so a failure is a
/// bug in the generator or a missing `rustfmt`.
pub fn format(source: &str) -> String {
    let mut rustfmt = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("run rustfmt");
    rustfmt
        .stdin
        .take()
        .expect("rustfmt reads stdin")
        .write_all(source.as_bytes())
        .expect("write the generated endpoints to rustfmt");
    let output = rustfmt.wait_with_output().expect("wait for rustfmt");
    assert!(
        output.status.success(),
        "rustfmt rejected the generated endpoints:\n{source}"
    );
    String::from_utf8(output.stdout).expect("rustfmt writes UTF-8")
}

/// The endpoints of `manifest` in registration order, once every name and interface type is checked.
fn endpoints(
    manifest: Manifest,
    messages: &BTreeSet<String>,
) -> Result<Vec<Endpoint>, ManifestError> {
    check_name(&manifest.service)?;
    let raw = manifest
        .job
        .into_iter()
        .map(|(name, entry)| {
            (
                Kind::Job,
                name,
                entry.interface_type,
                entry.custom,
                entry.nature,
            )
        })
        .chain(manifest.query.into_iter().map(|(name, entry)| {
            let kind = if entry.io { Kind::IoQuery } else { Kind::Query };
            (kind, name, entry.interface_type, false, None)
        }))
        .chain(
            manifest
                .state
                .into_iter()
                .map(|(name, entry)| (Kind::State, name, entry.interface_type, false, None)),
        )
        .chain(
            manifest
                .event
                .into_iter()
                .map(|(name, entry)| (Kind::Event, name, entry.interface_type, false, None)),
        );
    let mut functions = BTreeMap::new();
    let mut endpoints = Vec::new();
    for (kind, name, interface_type, custom, nature) in raw {
        check_name(&name)?;
        let function = name.to_case(Case::Snake);
        if STANDARD_ENDPOINTS
            .iter()
            .any(|standard| standard.name.to_case(Case::Snake) == function)
        {
            return Err(ManifestError::Reserved(name));
        }
        let endpoint = Endpoint {
            interface: interface(&name, kind, interface_type, messages)?,
            kind,
            name,
            function,
            custom,
            nature,
        };
        for function in endpoint.functions() {
            if let Some(first) = functions.insert(function.clone(), endpoint.name.clone()) {
                return Err(ManifestError::Duplicate {
                    first,
                    second: endpoint.name,
                    function,
                });
            }
        }
        endpoints.push(endpoint);
    }
    Ok(endpoints)
}

/// Accepts a name that is an identifier in both its spelling and its snake case.
fn check_name(name: &str) -> Result<(), ManifestError> {
    let plain = name.starts_with(|character: char| character.is_ascii_alphabetic())
        && name
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_');
    if plain && syn::parse_str::<syn::Ident>(&name.to_case(Case::Snake)).is_ok() {
        Ok(())
    } else {
        Err(ManifestError::InvalidName(name.to_owned()))
    }
}

/// The interface type `interface_type` of the endpoint `endpoint`, once `messages` is known to hold its parts: a
/// `.action` for a Job type, a `.srv` for a Query and a `.msg` for a State or an Event.
fn interface(
    endpoint: &str,
    kind: Kind,
    interface_type: String,
    messages: &BTreeSet<String>,
) -> Result<InterfaceType, ManifestError> {
    let (form, expected, part) = match kind {
        Kind::Job => ("action", ".action", "Goal"),
        Kind::Query | Kind::IoQuery => ("srv", ".srv", "Request"),
        Kind::State | Kind::Event => ("msg", ".msg", ""),
    };
    let interface = interface_type
        .split_once(&format!("/{form}/"))
        .map(|(package, name)| InterfaceType {
            package: package.to_owned(),
            form,
            name: name.to_owned(),
        });
    match interface {
        Some(interface) if messages.contains(&interface.part_schema_name(part)) => Ok(interface),
        _ => Err(ManifestError::UnknownType {
            endpoint: endpoint.to_owned(),
            interface_type,
            expected,
        }),
    }
}

fn api_source(service: &str, endpoints: &[Endpoint]) -> String {
    let mut source = format!(
        "//! The conversions between the Messages and the Domain of the `{service}` Service, one function per \
         endpoint.\n//!\n{GENERATED_NOTICE}"
    );
    let mut methods = String::new();
    let mut notes = Vec::new();
    let mut packages = BTreeSet::new();
    for endpoint in endpoints {
        let (function, key, title) = (&endpoint.function, endpoint.key(service), endpoint.title());
        let interface = &endpoint.interface;
        match endpoint.kind {
            Kind::Job => {
                let mut goal_mapping = String::new();
                if !endpoint.custom {
                    let error = format!("{}Error", endpoint.name.to_case(Case::UpperCamel));
                    let (job_id, goal) = (endpoint.job_id_parameter(), interface.path("Goal"));
                    _ = writeln!(
                        methods,
                        "/// Why a Goal of the {title} is rejected.\ntype {error}: core::error::Error + Send + Sync + \
                         'static;\n\n/// The {title}, at `{key}`.\n///\n/// The Domain's Request for the Goal, or why \
                         it is rejected.\nfn {function}({job_id}goal: {goal}) -> Result<Self::Request, \
                         Self::{error}>;\n"
                    );
                    goal_mapping = format!("`{error}`, `{function}`, ");
                }
                _ = writeln!(
                    methods,
                    "/// The Feedback of a Job of the {title}.\n///\n/// That of the Job `job_id` in `snapshot`, or \
                     `None` while it has none.\nfn {function}_feedback(snapshot: &Self::Snapshot, job_id: JobId) -> \
                     Option<{feedback}>;\n\n/// The Job result of a Job of the {title}.\n///\n/// That of the Job \
                     `job_id`, in the `snapshot` of the step that ended it.\nfn {function}_result(snapshot: \
                     &Self::Snapshot, job_id: JobId) -> {result};\n",
                    feedback = interface.path("Feedback"),
                    result = interface.path("Result"),
                );
                notes.push(format!(
                    "{goal_mapping}`{function}_feedback` and `{function}_result` for the {title}"
                ));
            }
            Kind::Query => {
                _ = writeln!(
                    methods,
                    "/// The {title}, at `{key}`.\n///\n/// The Domain's Query for the request.\nfn {function}(request: \
                     {request}) -> Self::Query;\n\n/// The reply of the {title}.\n///\n/// The response for \
                     `response`, or `None` when `response` answers another Query.\nfn {function}_response(response: \
                     Self::Response) -> Option<{response}>;\n",
                    request = interface.path("Request"),
                    response = interface.path("Response"),
                );
                notes.push(format!(
                    "`{function}` and `{function}_response` for the {title}"
                ));
            }
            Kind::State => {
                _ = writeln!(
                    methods,
                    "/// The {title}, at `{key}`.\n///\n/// Its value for `snapshot`.\nfn {function}(snapshot: \
                     &Self::Snapshot) -> {message};\n",
                    message = interface.path(""),
                );
                notes.push(format!("`{function}` for the {title}"));
            }
            Kind::Event => {
                _ = writeln!(
                    methods,
                    "/// The {title}, at `{key}`.\n///\n/// What it publishes for `event`, or `None` when `event` is \
                     another one.\nfn {function}(event: &Self::Event) -> Option<{message}>;\n",
                    message = interface.path(""),
                );
                notes.push(format!("`{function}` for the {title}"));
            }
            Kind::IoQuery => continue,
        }
        packages.insert(interface.package.clone());
    }
    if methods.is_empty() {
        return source;
    }
    let domain = domain_trait(endpoints);
    let list = notes.join(", ");
    let jobs = if endpoints.iter().any(|endpoint| endpoint.kind == Kind::Job) {
        "use blueos_jobs::JobId;\n"
    } else {
        ""
    };
    _ = write!(
        source,
        "\nuse blueos_domain::{domain};\nuse blueos_idl::msg::{{{packages}}};\n{jobs}\n/// Converts between the Domain and \
         the Messages of every endpoint of the `{service}` Service but its IO\n/// queries. Implement it for the \
         Domain in this crate: `register` in the app crate calls it.\n#[diagnostic::on_unimplemented(\nmessage = \
         \"`{{Self}}` does not convert the endpoints of the `{service}` Service\",\nlabel = \"no `impl \
         Conversions for {{Self}}` in the `{service}` logic/api crate\",\nnote = \"implement {list}\"\n)]\npub \
         trait Conversions: {domain} {{\n{methods}}}\n",
        packages = packages.into_iter().collect::<Vec<_>>().join(", "),
    );
    source
}

fn app_source(service: &str, api_crate: &str, endpoints: &[Endpoint]) -> String {
    let conversions = endpoints
        .iter()
        .any(|endpoint| endpoint.kind != Kind::IoQuery);
    let handled: Vec<&Endpoint> = endpoints
        .iter()
        .filter(|endpoint| endpoint.is_handled())
        .collect();
    let mut packages = BTreeSet::new();
    let mut methods = String::new();
    for endpoint in &handled {
        let (function, key, title) = (&endpoint.function, endpoint.key(service), endpoint.title());
        let interface = &endpoint.interface;
        let (description, parameter, output) = match endpoint.kind {
            Kind::Job => (
                "The Domain's Request for the Goal",
                format!(
                    "{}goal: {}",
                    endpoint.job_id_parameter(),
                    interface.path("Goal")
                ),
                "Result<D::Request, Refusal>".to_owned(),
            ),
            Kind::Query | Kind::IoQuery | Kind::State | Kind::Event => (
                "Its response, read outside the Inbox",
                format!("request: {}", interface.path("Request")),
                format!(
                    "impl Future<Output = Result<{}, Refusal>> + Send",
                    interface.path("Response")
                ),
            ),
        };
        _ = writeln!(
            methods,
            "/// The {title}, at `{key}`.\n///\n/// {description}, or why it is refused.\nfn {function}(&self, \
             {parameter}) -> {output};\n"
        );
    }
    let mut registrations = String::new();
    for endpoint in endpoints {
        let (name, function) = (&endpoint.name, &endpoint.function);
        let interface = &endpoint.interface;
        let registration = match endpoint.kind {
            Kind::Job => {
                let goal = interface.path("Goal");
                let job_id = if endpoint.nature.is_some() {
                    "job_id, "
                } else {
                    ""
                };
                let into_request = if endpoint.custom {
                    format!(
                        "{{\nlet handlers = Arc::clone(&handlers);\nmove |{job_id}goal: {goal}| \
                         H::{function}(&handlers, {job_id}goal)\n}}"
                    )
                } else {
                    format!(
                        "|{job_id}goal: {goal}| <D as Conversions>::{function}({job_id}goal).map_err(Refusal::from)"
                    )
                };
                let job_type = match endpoint.nature {
                    Some(nature) => format!(
                        ".job(\"{name}\", JobNature {{ lasting: {}, cancellable: {}, pausable: {}, \
                         needs_permission: {} }}, {into_request})",
                        nature.lasting,
                        nature.cancellable,
                        nature.pausable,
                        nature.needs_permission
                    ),
                    None => format!(".command(\"{name}\", {into_request})"),
                };
                format!(
                    "{job_type}\n.job_feedback(\"{name}\", <D as Conversions>::{function}_feedback)\n\
                     .job_result(\"{name}\", <D as Conversions>::{function}_result)"
                )
            }
            Kind::Query => format!(
                ".query(\"{name}\", |request: {request}| Ok(<D as Conversions>::{function}(request)), <D as \
                 Conversions>::{function}_response)",
                request = interface.path("Request"),
            ),
            Kind::IoQuery => format!(
                ".io_query(\"{name}\", {{\nlet handlers = Arc::clone(&handlers);\nmove |request: {request}| \
                 {{\nlet handlers = Arc::clone(&handlers);\nBox::pin(async move {{ H::{function}(&handlers, \
                 request).await }})\n}}\n}})",
                request = interface.path("Request"),
            ),
            Kind::State => format!(".state(\"{name}\", <D as Conversions>::{function})"),
            Kind::Event => format!(".event(\"{name}\", <D as Conversions>::{function})"),
        };
        _ = writeln!(registrations, "{registration}");
        if matches!(endpoint.kind, Kind::Job | Kind::Query | Kind::IoQuery) {
            packages.insert(interface.package.clone());
        }
    }
    let domain = domain_trait(endpoints);
    let mut imports = String::new();
    if handled
        .iter()
        .any(|endpoint| endpoint.kind == Kind::IoQuery)
    {
        imports.push_str("use core::future::Future;\n");
    }
    if !handled.is_empty() {
        imports.push_str("use std::sync::Arc;\n\n");
    }
    if !handled.is_empty() || !conversions {
        _ = writeln!(imports, "use blueos_domain::{domain};");
    }
    if !packages.is_empty() {
        _ = writeln!(
            imports,
            "use blueos_idl::msg::{{{}}};",
            packages.into_iter().collect::<Vec<_>>().join(", ")
        );
    }
    let jobs = endpoints.iter().any(|endpoint| endpoint.nature.is_some());
    if jobs {
        let job_id = if handled.iter().any(|endpoint| endpoint.nature.is_some()) {
            "JobId, "
        } else {
            ""
        };
        _ = writeln!(
            imports,
            "use blueos_jobs::{{DomainJobs, {job_id}JobNature}};"
        );
    }
    let refusal = if !handled.is_empty()
        || endpoints
            .iter()
            .any(|endpoint| endpoint.kind == Kind::Job && !endpoint.custom)
    {
        "Refusal, "
    } else {
        ""
    };
    _ = writeln!(imports, "use blueos_service::{{{refusal}ServiceBuilder}};");
    if conversions {
        _ = writeln!(imports, "use {api_crate}::endpoints::Conversions;");
    }
    let mut source = format!(
        "//! The endpoints of the `{service}` Service, registered as `endpoints.toml` lists them.\n//!\n\
         {GENERATED_NOTICE}\n{imports}\n/// The name of the `{service}` Service, in each of its keys: \
         `blueos/v1/{service}/...`.\npub const NAME: &str = \"{service}\";\n"
    );
    let manifest_endpoints = manifest_endpoints_vec_source(endpoints, service);
    let bound = match (conversions, jobs) {
        (true, true) => "Conversions + DomainJobs".to_owned(),
        (true, false) => "Conversions".to_owned(),
        (false, true) => format!("{domain} + DomainJobs"),
        (false, false) => domain.to_owned(),
    };
    let manifest_tail = format!("\n.manifest_endpoints({manifest_endpoints})");
    if handled.is_empty() {
        _ = write!(
            source,
            "\n/// Registers every endpoint of `endpoints.toml` on `builder`.\npub fn register<D: {bound}, Context>(builder: \
             ServiceBuilder<D, Context>) -> ServiceBuilder<D, Context> {{\nbuilder\n{registrations}{manifest_tail}\n}}\n"
        );
        return source;
    }
    let list = handled
        .iter()
        .map(|endpoint| format!("`{}` for the {}", endpoint.function, endpoint.title()))
        .collect::<Vec<_>>()
        .join(", ");
    _ = write!(
        source,
        "\n/// Handles the endpoints of the `{service}` Service whose mapping is not a plain conversion: the \
         `custom`\n/// Job types and the IO queries. Implement it in `handlers.rs` and pass it to \
         [`register`].\n#[diagnostic::on_unimplemented(\nmessage = \"`{{Self}}` does not handle the custom \
         endpoints of the `{service}` Service\",\nlabel = \"no `impl Handlers<D> for {{Self}}` in the \
         `{service}` app crate\",\nnote = \"implement {list}\"\n)]\npub trait Handlers<D: {domain}>: Send + Sync + \
         'static {{\n{methods}}}\n\n/// Registers every endpoint of `endpoints.toml` on `builder`, with `handlers` \
         for the custom ones.\npub fn register<D: {bound}, H: Handlers<D>, Context>(builder: ServiceBuilder<D, \
         Context>, handlers: H) -> ServiceBuilder<D, Context> {{\nlet handlers = Arc::new(handlers);\nbuilder\n{registrations}{manifest_tail}\n}}\n"
    );
    source
}

fn manifest_endpoints_vec_source(endpoints: &[Endpoint], service: &str) -> String {
    if endpoints.is_empty() {
        return "vec![]".to_owned();
    }
    let mut rows = String::new();
    for endpoint in endpoints {
        _ = writeln!(
            rows,
            "        blueos_idl::msg::blueos_msgs::EndpointInfo {{\n            kind: \"{kind}\".into(),\n            \
             name: \"{name}\".into(),\n            key: \"{key}\".into(),\n            interface_type: \
             \"{interface_type}\".into(),\n            schema: \
             blueos_idl::schema(\"{interface_type}\").unwrap_or_default().into(),\n        }},",
            kind = endpoint.kind_name(),
            name = endpoint.name,
            key = endpoint.key(service),
            interface_type = endpoint.interface.schema_name(),
        );
    }
    format!("vec![\n{rows}    ]")
}

fn domain_trait(endpoints: &[Endpoint]) -> &'static str {
    if endpoints
        .iter()
        .any(|endpoint| endpoint.kind == Kind::Query)
    {
        "DomainQueries"
    } else {
        "Domain"
    }
}

fn typescript_client_source(service: &str, endpoints: &[Endpoint]) -> String {
    let mut key_helpers = BTreeSet::new();
    for endpoint in endpoints {
        let helper = match endpoint.kind {
            Kind::Job => "commandKey",
            Kind::Query | Kind::IoQuery => "queryKey",
            Kind::State => "stateKey",
            Kind::Event => "eventKey",
        };
        key_helpers.insert(helper);
    }
    let mut source = format!("{TYPESCRIPT_GENERATED_NOTICE}\n");
    if !endpoints.is_empty() {
        source.push_str("import type * as Idl from '@blueos-idl/messages'\n\n");
    }
    if !key_helpers.is_empty() {
        let helpers = key_helpers.into_iter().collect::<Vec<_>>().join(",\n  ");
        _ = write!(
            source,
            "import {{\n  {helpers},\n}} from '../keys'\n",
            helpers = helpers
        );
    }
    _ = write!(
        source,
        "\n/** The name of the `{service}` Service, in each of its keys: `blueos/v1/{service}/...`. */\nexport const NAME = \
         '{service}'\n"
    );
    for endpoint in endpoints {
        let name = &endpoint.name;
        let export_name = typescript_export_name(name);
        let key_helper = match endpoint.kind {
            Kind::Job => "commandKey",
            Kind::Query | Kind::IoQuery => "queryKey",
            Kind::State => "stateKey",
            Kind::Event => "eventKey",
        };
        let kind = endpoint.kind_name();
        let key = endpoint.key(service);
        let interface = &endpoint.interface;
        _ = write!(
            source,
            "\n/** {kind} `{name}` at `{key}`. */\nexport const {export_name} = {{\n  kind: '{kind}' as const,\n  name: \
             '{name}',\n  key: {key_helper}(NAME, '{name}'),\n  type: '{}' as const,\n",
            interface.schema_name()
        );
        let parts: &[(&str, &str)] = match endpoint.kind {
            Kind::Job => &[
                ("goalSchema", "Goal"),
                ("feedbackSchema", "Feedback"),
                ("resultSchema", "Result"),
            ],
            Kind::Query | Kind::IoQuery => {
                &[("requestSchema", "Request"), ("responseSchema", "Response")]
            }
            Kind::State | Kind::Event => &[("messageSchema", "")],
        };
        for (field, part) in parts {
            _ = writeln!(
                source,
                "  {field}: '{}' as const,",
                interface.part_schema_name(part)
            );
        }
        source.push_str("}\n");
        for (_, part) in parts {
            let type_name = if part.is_empty() {
                typescript_type_name(name)
            } else {
                format!("{export_name}{part}")
            };
            _ = writeln!(
                source,
                "export type {type_name} = Idl.{}",
                interface.typescript_type(part)
            );
        }
    }
    source
}

fn typescript_export_name(name: &str) -> String {
    name.to_owned()
}

fn typescript_type_name(name: &str) -> String {
    name.to_case(Case::UpperCamel)
}
