//! Generates each Service's endpoint registration from its endpoint manifest (D-26).
//!
//! A Service's app crate commits `endpoints.toml`, next to its `Cargo.toml`. From it the generator writes two
//! committed files: `logic/api/src/endpoints.rs`, the `Conversions` trait its Domain implements, and
//! `app/src/endpoints.rs`, the Service `NAME`, the `Handlers` trait of the `custom` endpoints and `register`.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs, io,
    io::Write as _,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use convert_case::{Case, Casing};
use serde::Deserialize;

/// The file name of an endpoint manifest, next to the `Cargo.toml` of a Service's app crate.
pub const MANIFEST_FILE: &str = "endpoints.toml";

/// Where the TypeScript clients are committed, under `core/`.
const TYPESCRIPT_DIR: &str = "frontend/src/libs/blueos-api/services";

/// The endpoints D-12 gives every Service. A manifest cannot reuse their names, and `api.lock` records them for
/// every Service.
// ponytail: records `settings`, `UpdateSettings` and `jobs` for every Service, as the generator cannot see a
// `ServiceBuilder::settings` or `ServiceBuilder::jobs` opt-in; a manifest field would make the lock exact.
const STANDARD_ENDPOINTS: [StandardEndpoint; 6] = [
    StandardEndpoint {
        name: "info",
        key: "query/info",
        request_schema: "",
        response_schema: "blueos_msgs/msg/ServiceInfo",
    },
    StandardEndpoint {
        name: "status",
        key: "state/status",
        request_schema: "",
        response_schema: "blueos_msgs/msg/ServiceStatus",
    },
    StandardEndpoint {
        name: "settings",
        key: "settings",
        request_schema: "",
        response_schema: "blueos_msgs/msg/SettingsEnvelope",
    },
    StandardEndpoint {
        name: "UpdateSettings",
        key: "command/UpdateSettings",
        request_schema: "blueos_msgs/msg/SettingsEnvelope",
        response_schema: COMMAND_ACK_SCHEMA,
    },
    StandardEndpoint {
        name: "log",
        key: "log",
        request_schema: "",
        response_schema: "foxglove_msgs/msg/Log",
    },
    StandardEndpoint {
        name: "jobs",
        key: "jobs",
        request_schema: "",
        response_schema: "blueos_msgs/msg/JobList",
    },
];

const COMMAND_ACK_SCHEMA: &str = "blueos_msgs/msg/CommandAck";

const GENERATED_NOTICE: &str = "//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not \
                                edit it: change\n//! the manifest and run `cargo run -p blueos-idl-codegen -- \
                                --write` in `core/`.\n";

const TYPESCRIPT_GENERATED_NOTICE: &str = "// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. \
                                          Do not edit: change\n// the manifest and run `cargo run -p blueos-idl-codegen \
                                          -- --write` in `core/`.\n";

/// Why the generator could not generate the endpoint files of the workspace.
#[derive(Debug, thiserror::Error)]
pub enum EndpointsError {
    /// A file could not be read.
    #[error("{}: {error}", path.display())]
    Read {
        /// The file.
        path: PathBuf,
        /// Why it could not be read.
        error: io::Error,
    },
    /// A `Cargo.toml` does not parse, or misses the field the generator needs.
    #[error("{}: {reason}", path.display())]
    Cargo {
        /// The `Cargo.toml`.
        path: PathBuf,
        /// What is wrong with it.
        reason: String,
    },
    /// An endpoint manifest is wrong.
    #[error("{}: {error}", path.display())]
    Manifest {
        /// The manifest.
        path: PathBuf,
        /// What is wrong with it.
        error: ManifestError,
    },
}

/// What is wrong with an endpoint manifest.
#[derive(Debug, PartialEq, Eq, thiserror::Error)]
pub enum ManifestError {
    /// The manifest is not valid TOML, or has a field the format does not have.
    #[error("the manifest does not parse: {0}")]
    Parse(String),
    /// A Service or endpoint name is not a plain identifier.
    #[error(
        "`{0}` is not a valid name: use ASCII letters, digits and `_`, start with a letter, and avoid Rust keywords"
    )]
    InvalidName(String),
    /// An endpoint uses a name every Service already has (D-12).
    #[error("the endpoint `{0}` uses a name every Service already has (D-12)")]
    Reserved(String),
    /// Two endpoints generate the same function.
    #[error(
        "the endpoints `{first}` and `{second}` both generate `{function}`: endpoint names are unique in a Service"
    )]
    Duplicate {
        /// The endpoint listed first.
        first: String,
        /// The endpoint listed second.
        second: String,
        /// The function both generate.
        function: String,
    },
    /// An endpoint uses a Message that is not in `core/libs/idl/interfaces`.
    #[error("the endpoint `{endpoint}` uses `{message}`, which is not a Message of `blueos-idl`")]
    UnknownMessage {
        /// The endpoint.
        endpoint: String,
        /// The Message schema name it gave, `<package>/msg/<Name>`.
        message: String,
    },
}

/// A generated file and what it should contain.
#[derive(Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Where the file is committed.
    pub path: PathBuf,
    /// Its formatted text.
    pub contents: String,
}

/// The generated sources of one manifest, before formatting.
#[derive(Debug)]
pub struct Generated {
    /// The Service name from the manifest.
    pub service: String,
    /// `logic/api/src/endpoints.rs`: the `Conversions` trait.
    pub api: String,
    /// `app/src/endpoints.rs`: `NAME`, the `Handlers` trait and `register`.
    pub app: String,
    /// `frontend/src/libs/blueos-api/services/<service>.ts`: keys and Message types (D-14).
    pub typescript: String,
}

/// `endpoints.toml`. Each table maps an endpoint name to its Message types, in sorted order.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Manifest {
    service: String,
    #[serde(default)]
    command: BTreeMap<String, CommandEntry>,
    #[serde(default)]
    query: BTreeMap<String, QueryEntry>,
    #[serde(default)]
    io_query: BTreeMap<String, IoQueryEntry>,
    #[serde(default)]
    state: BTreeMap<String, PublishedEntry>,
    #[serde(default)]
    event: BTreeMap<String, PublishedEntry>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CommandEntry {
    request: String,
    #[serde(default)]
    custom: bool,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct QueryEntry {
    request: String,
    response: String,
    #[serde(default)]
    custom: bool,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct IoQueryEntry {
    request: String,
    response: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct PublishedEntry {
    message: String,
}

/// One manifest endpoint, for `api.lock` and the generated `info` list.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct EndpointInfoRow {
    pub kind: &'static str,
    pub name: String,
    pub key: String,
    pub request_schema: String,
    pub response_schema: String,
}

/// One endpoint of the manifest, with the Messages it takes and sends.
struct Endpoint {
    kind: Kind,
    name: String,
    function: String,
    request: Option<MessageType>,
    reply: Option<MessageType>,
    custom: bool,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Kind {
    Command,
    Query,
    IoQuery,
    State,
    Event,
}

/// A Message, from its schema name `<package>/msg/<Name>`.
struct MessageType {
    package: String,
    name: String,
}

/// An endpoint the Kernel declares for a Service, at `blueos/v1/<service>/<key>`.
struct StandardEndpoint {
    name: &'static str,
    key: &'static str,
    request_schema: &'static str,
    response_schema: &'static str,
}

impl Endpoint {
    fn key(&self, service: &str) -> String {
        let segment = match self.kind {
            Kind::Command => "command",
            Kind::Query | Kind::IoQuery => "query",
            Kind::State => "state",
            Kind::Event => "event",
        };
        format!("blueos/v1/{service}/{segment}/{}", self.name)
    }

    fn title(&self) -> String {
        let kind = match self.kind {
            Kind::Command => "Command",
            Kind::Query => "Query",
            Kind::IoQuery => "IO query",
            Kind::State => "State",
            Kind::Event => "Event",
        };
        format!("{kind} `{}`", self.name)
    }

    fn is_handled(&self) -> bool {
        self.custom || self.kind == Kind::IoQuery
    }

    /// The functions it generates in `Conversions` and `Handlers`, which must be unique in a Service.
    fn functions(&self) -> Vec<String> {
        let mut functions = vec![self.function.clone()];
        if self.kind == Kind::Query {
            functions.push(format!("{}_response", self.function));
        }
        functions
    }

    fn request(&self) -> String {
        self.request
            .as_ref()
            .map(MessageType::path)
            .unwrap_or_default()
    }

    fn reply(&self) -> String {
        self.reply
            .as_ref()
            .map(MessageType::path)
            .unwrap_or_default()
    }

    fn kind_name(&self) -> &'static str {
        match self.kind {
            Kind::Command => "command",
            Kind::Query => "query",
            Kind::IoQuery => "io_query",
            Kind::State => "state",
            Kind::Event => "event",
        }
    }

    fn request_schema(&self) -> String {
        self.request
            .as_ref()
            .map(MessageType::schema_name)
            .unwrap_or_default()
    }

    fn response_schema(&self) -> String {
        match self.kind {
            Kind::Command => COMMAND_ACK_SCHEMA.to_owned(),
            Kind::Query | Kind::IoQuery | Kind::State | Kind::Event => self
                .reply
                .as_ref()
                .map(MessageType::schema_name)
                .unwrap_or_default(),
        }
    }

    fn lock_signature(&self) -> String {
        format!(
            "request={};response={}",
            self.request_schema(),
            self.response_schema()
        )
    }

    fn endpoint_info(&self, service: &str) -> EndpointInfoRow {
        EndpointInfoRow {
            kind: self.kind_name(),
            name: self.name.clone(),
            key: self.key(service),
            request_schema: self.request_schema(),
            response_schema: self.response_schema(),
        }
    }
}

impl MessageType {
    fn path(&self) -> String {
        format!("{}::{}", self.package, self.name)
    }

    fn schema_name(&self) -> String {
        format!("{}/msg/{}", self.package, self.name)
    }

    fn typescript_type(&self) -> &str {
        &self.name
    }
}

/// Every endpoint key of the Services in workspace manifests, with the standard ones, for `api.lock`.
pub fn collect_endpoint_lock_lines(
    core_dir: &Path,
    messages: &BTreeSet<String>,
) -> Result<Vec<String>, EndpointsError> {
    let mut lines = Vec::new();
    for (service, endpoints) in collect_service_endpoints(core_dir, messages)? {
        for standard in &STANDARD_ENDPOINTS {
            lines.push(crate::format_lock_line(
                &format!("blueos/v1/{service}/{}", standard.key),
                1,
                &format!(
                    "request={};response={}",
                    standard.request_schema, standard.response_schema
                ),
            ));
        }
        for endpoint in endpoints {
            lines.push(crate::format_lock_line(
                &endpoint.key(&service),
                1,
                &endpoint.lock_signature(),
            ));
        }
    }
    lines.sort();
    Ok(lines)
}

fn collect_service_endpoints(
    core_dir: &Path,
    messages: &BTreeSet<String>,
) -> Result<Vec<(String, Vec<Endpoint>)>, EndpointsError> {
    let mut collected = Vec::new();
    for member in workspace_members(core_dir)? {
        let manifest_path = core_dir.join(member).join(MANIFEST_FILE);
        if !manifest_path.is_file() {
            continue;
        }
        let manifest = read_manifest(&manifest_path)?;
        let service = manifest.service.clone();
        let service_endpoints =
            endpoints(manifest, messages).map_err(|error| EndpointsError::Manifest {
                path: manifest_path.clone(),
                error,
            })?;
        collected.push((service, service_endpoints));
    }
    Ok(collected)
}

fn read_manifest(path: &Path) -> Result<Manifest, EndpointsError> {
    let source = fs::read_to_string(path).map_err(|error| EndpointsError::Read {
        path: path.to_owned(),
        error,
    })?;
    toml::from_str(&source).map_err(|error| EndpointsError::Manifest {
        path: path.to_owned(),
        error: ManifestError::Parse(error.to_string()),
    })
}

/// Generates the endpoint files of every Service in the workspace at `core_dir`. `messages` holds the schema name
/// of every Message of `blueos-idl`.
pub fn generate_all(
    core_dir: &Path,
    messages: &BTreeSet<String>,
) -> Result<Vec<GeneratedFile>, EndpointsError> {
    let mut files = Vec::new();
    for member in workspace_members(core_dir)? {
        let app_dir = core_dir.join(member);
        let manifest_path = app_dir.join(MANIFEST_FILE);
        if !manifest_path.exists() {
            continue;
        }
        let api_dir = app_dir.with_file_name("logic").join("api");
        let api_cargo = api_dir.join("Cargo.toml");
        let api_crate = read_toml(&api_cargo)?
            .get("package")
            .and_then(|package| package.get("name"))
            .and_then(toml::Value::as_str)
            .ok_or_else(|| EndpointsError::Cargo {
                path: api_cargo.clone(),
                reason: "no `package.name`".to_owned(),
            })?
            .replace('-', "_");
        let generated =
            generate(&read(&manifest_path)?, &api_crate, messages).map_err(|error| {
                EndpointsError::Manifest {
                    path: manifest_path.clone(),
                    error,
                }
            })?;
        let typescript_dir = core_dir.join(TYPESCRIPT_DIR);
        fs::create_dir_all(&typescript_dir).map_err(|error| EndpointsError::Read {
            path: typescript_dir.clone(),
            error,
        })?;
        let typescript_path = typescript_dir.join(format!("{}.ts", generated.service));
        for (path, source, format_rust) in [
            (api_dir.join("src/endpoints.rs"), generated.api, true),
            (app_dir.join("src/endpoints.rs"), generated.app, true),
            (typescript_path, generated.typescript, false),
        ] {
            files.push(GeneratedFile {
                path,
                contents: if format_rust { format(&source) } else { source },
            });
        }
    }
    Ok(files)
}

/// The generated endpoint files under `core_dir` that `generated` does not list: the TypeScript client or the
/// wiring of a crate whose `endpoints.toml` is gone.
pub fn stray_files(
    core_dir: &Path,
    generated: &[GeneratedFile],
) -> Result<Vec<PathBuf>, EndpointsError> {
    let clients = fs::read_dir(core_dir.join(TYPESCRIPT_DIR))
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path());
    let wiring = workspace_members(core_dir)?
        .into_iter()
        .map(|member| core_dir.join(member).join("src/endpoints.rs"));
    let mut stray = Vec::new();
    for path in clients.chain(wiring) {
        let contents = match fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(error) if error.kind() == io::ErrorKind::NotFound => continue,
            Err(error) => return Err(EndpointsError::Read { path, error }),
        };
        let is_generated =
            contents.contains(GENERATED_NOTICE) || contents.contains(TYPESCRIPT_GENERATED_NOTICE);
        if is_generated && !generated.iter().any(|file| file.path == path) {
            stray.push(path);
        }
    }
    stray.sort();
    Ok(stray)
}

/// Generates the two endpoint sources of the manifest `source`, whose `logic/api` crate is `api_crate` (in its
/// Rust spelling, with `_`).
pub fn generate(
    source: &str,
    api_crate: &str,
    messages: &BTreeSet<String>,
) -> Result<Generated, ManifestError> {
    let manifest: Manifest =
        toml::from_str(source).map_err(|error| ManifestError::Parse(error.to_string()))?;
    let service = manifest.service.clone();
    let endpoints = endpoints(manifest, messages)?;
    Ok(Generated {
        api: api_source(&service, &endpoints),
        app: app_source(&service, api_crate, &endpoints),
        typescript: typescript_client_source(&service, &endpoints),
        service,
    })
}

/// The `workspace.members` of the `Cargo.toml` at `core_dir`.
fn workspace_members(core_dir: &Path) -> Result<Vec<String>, EndpointsError> {
    let workspace = read_toml(&core_dir.join("Cargo.toml"))?;
    let members = workspace
        .get("workspace")
        .and_then(|workspace| workspace.get("members"))
        .and_then(toml::Value::as_array)
        .ok_or_else(|| EndpointsError::Cargo {
            path: core_dir.join("Cargo.toml"),
            reason: "no `workspace.members` list".to_owned(),
        })?;
    Ok(members
        .iter()
        .filter_map(toml::Value::as_str)
        .map(str::to_owned)
        .collect())
}

fn read_toml(path: &Path) -> Result<toml::Table, EndpointsError> {
    read(path)?
        .parse()
        .map_err(|error: toml::de::Error| EndpointsError::Cargo {
            path: path.to_path_buf(),
            reason: error.to_string(),
        })
}

fn read(path: &Path) -> Result<String, EndpointsError> {
    fs::read_to_string(path).map_err(|error| EndpointsError::Read {
        path: path.to_path_buf(),
        error,
    })
}

/// Formats a generated source with `rustfmt`, as `cargo fmt` would. The source always parses, so a failure is a
/// bug in the generator or a missing `rustfmt`.
fn format(source: &str) -> String {
    let mut rustfmt = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("run rustfmt");
    rustfmt
        .stdin
        .take()
        .expect("rustfmt reads stdin")
        .write_all(source.as_bytes())
        .expect("write the generated endpoints to rustfmt");
    let output = rustfmt.wait_with_output().expect("wait for rustfmt");
    assert!(
        output.status.success(),
        "rustfmt rejected the generated endpoints:\n{source}"
    );
    String::from_utf8(output.stdout).expect("rustfmt writes UTF-8")
}

/// The endpoints of `manifest` in registration order, once every name and Message is checked.
fn endpoints(
    manifest: Manifest,
    messages: &BTreeSet<String>,
) -> Result<Vec<Endpoint>, ManifestError> {
    check_name(&manifest.service)?;
    let raw = manifest
        .command
        .into_iter()
        .map(|(name, entry)| (Kind::Command, name, Some(entry.request), None, entry.custom))
        .chain(manifest.query.into_iter().map(|(name, entry)| {
            (
                Kind::Query,
                name,
                Some(entry.request),
                Some(entry.response),
                entry.custom,
            )
        }))
        .chain(manifest.io_query.into_iter().map(|(name, entry)| {
            (
                Kind::IoQuery,
                name,
                Some(entry.request),
                Some(entry.response),
                false,
            )
        }))
        .chain(
            manifest
                .state
                .into_iter()
                .map(|(name, entry)| (Kind::State, name, None, Some(entry.message), false)),
        )
        .chain(
            manifest
                .event
                .into_iter()
                .map(|(name, entry)| (Kind::Event, name, None, Some(entry.message), false)),
        );
    let mut functions = BTreeMap::new();
    let mut endpoints = Vec::new();
    for (kind, name, request, reply, custom) in raw {
        check_name(&name)?;
        let function = name.to_case(Case::Snake);
        if STANDARD_ENDPOINTS
            .iter()
            .any(|standard| standard.name.to_case(Case::Snake) == function)
        {
            return Err(ManifestError::Reserved(name));
        }
        let endpoint = Endpoint {
            request: request
                .map(|message| message_type(&name, message, messages))
                .transpose()?,
            reply: reply
                .map(|message| message_type(&name, message, messages))
                .transpose()?,
            kind,
            name,
            function,
            custom,
        };
        for function in endpoint.functions() {
            if let Some(first) = functions.insert(function.clone(), endpoint.name.clone()) {
                return Err(ManifestError::Duplicate {
                    first,
                    second: endpoint.name,
                    function,
                });
            }
        }
        endpoints.push(endpoint);
    }
    Ok(endpoints)
}

/// Accepts a name that is an identifier in both its spelling and its snake case.
fn check_name(name: &str) -> Result<(), ManifestError> {
    let plain = name.starts_with(|character: char| character.is_ascii_alphabetic())
        && name
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_');
    if plain && syn::parse_str::<syn::Ident>(&name.to_case(Case::Snake)).is_ok() {
        Ok(())
    } else {
        Err(ManifestError::InvalidName(name.to_owned()))
    }
}

fn message_type(
    endpoint: &str,
    message: String,
    messages: &BTreeSet<String>,
) -> Result<MessageType, ManifestError> {
    match message.split_once("/msg/") {
        Some((package, name)) if messages.contains(&message) => Ok(MessageType {
            package: package.to_owned(),
            name: name.to_owned(),
        }),
        _ => Err(ManifestError::UnknownMessage {
            endpoint: endpoint.to_owned(),
            message,
        }),
    }
}

fn api_source(service: &str, endpoints: &[Endpoint]) -> String {
    let mut source = format!(
        "//! The conversions between the Messages and the Domain of the `{service}` Service, one function per \
         endpoint.\n//!\n{GENERATED_NOTICE}"
    );
    let mut methods = String::new();
    let mut notes = Vec::new();
    let mut packages = BTreeSet::new();
    for endpoint in endpoints {
        let (function, key, title) = (&endpoint.function, endpoint.key(service), endpoint.title());
        let (request, reply) = (endpoint.request(), endpoint.reply());
        match endpoint.kind {
            Kind::Command | Kind::Query if !endpoint.custom => {
                let into = if endpoint.kind == Kind::Command {
                    "Request"
                } else {
                    "Query"
                };
                _ = writeln!(
                    methods,
                    "/// The {title}, at `{key}`.\n///\n/// The Domain's {into} for the Message.\nfn \
                     {function}(request: {request}) -> Self::{into};\n"
                );
                notes.push(format!("`{function}` for the {title}"));
            }
            Kind::Command | Kind::IoQuery | Kind::Query | Kind::State | Kind::Event => {}
        }
        match endpoint.kind {
            Kind::Query => {
                _ = writeln!(
                    methods,
                    "/// The reply of the {title}.\n///\n/// The Message for `response`, or `None` when `response` answers \
                     another Query.\nfn {function}_response(response: Self::Response) -> Option<{reply}>;\n"
                );
                notes.push(format!("`{function}_response` for the {title}"));
            }
            Kind::State => {
                _ = writeln!(
                    methods,
                    "/// The {title}, at `{key}`.\n///\n/// Its value for `snapshot`.\nfn {function}(snapshot: \
                     &Self::Snapshot) -> {reply};\n"
                );
                notes.push(format!("`{function}` for the {title}"));
            }
            Kind::Event => {
                _ = writeln!(
                    methods,
                    "/// The {title}, at `{key}`.\n///\n/// What it publishes for `event`, or `None` when `event` is \
                     another one.\nfn {function}(event: &Self::Event) -> Option<{reply}>;\n"
                );
                notes.push(format!("`{function}` for the {title}"));
            }
            Kind::Command | Kind::IoQuery => {}
        }
        if !endpoint.is_handled() {
            packages.extend(
                endpoint
                    .request
                    .iter()
                    .chain(&endpoint.reply)
                    .map(|message| message.package.clone()),
            );
        } else if endpoint.kind == Kind::Query {
            packages.extend(endpoint.reply.iter().map(|message| message.package.clone()));
        }
    }
    if methods.is_empty() {
        return source;
    }
    let domain = domain_trait(endpoints);
    let list = notes.join(", ");
    _ = write!(
        source,
        "\nuse blueos_domain::{domain};\nuse blueos_idl::msg::{{{packages}}};\n\n/// Converts between the Domain and \
         the Messages of every endpoint of the `{service}` Service that is not\n/// `custom`. Implement it for the \
         Domain in this crate: `register` in the app crate calls it.\n#[diagnostic::on_unimplemented(\nmessage = \
         \"`{{Self}}` does not convert the endpoints of the `{service}` Service\",\nlabel = \"no `impl \
         Conversions for {{Self}}` in the `{service}` logic/api crate\",\nnote = \"implement {list}\"\n)]\npub \
         trait Conversions: {domain} {{\n{methods}}}\n",
        packages = packages.into_iter().collect::<Vec<_>>().join(", "),
    );
    source
}

fn app_source(service: &str, api_crate: &str, endpoints: &[Endpoint]) -> String {
    let conversions = endpoints
        .iter()
        .any(|endpoint| !endpoint.is_handled() || endpoint.kind == Kind::Query);
    let handled: Vec<&Endpoint> = endpoints
        .iter()
        .filter(|endpoint| endpoint.is_handled())
        .collect();
    let mut packages = BTreeSet::new();
    let mut methods = String::new();
    for endpoint in &handled {
        let (function, key, title) = (&endpoint.function, endpoint.key(service), endpoint.title());
        let (request, reply) = (endpoint.request(), endpoint.reply());
        let (description, output) = match endpoint.kind {
            Kind::Command => (
                "The Domain's Request for the Message",
                "Result<D::Request, Refusal>".to_owned(),
            ),
            Kind::Query => (
                "The Domain's Query for the Message",
                "Result<D::Query, Refusal>".to_owned(),
            ),
            Kind::IoQuery | Kind::State | Kind::Event => (
                "Its reply, read outside the Inbox",
                format!("impl Future<Output = Result<{reply}, Refusal>> + Send"),
            ),
        };
        _ = writeln!(
            methods,
            "/// The {title}, at `{key}`.\n///\n/// {description}, or why it is refused.\nfn {function}(&self, \
             request: {request}) -> {output};\n"
        );
    }
    let mut registrations = String::new();
    for endpoint in endpoints {
        let (name, function) = (&endpoint.name, &endpoint.function);
        let request = endpoint.request();
        let handler = format!(
            "{{\nlet handlers = Arc::clone(&handlers);\nmove |request: {request}| H::{function}(&handlers, \
             request)\n}}"
        );
        let conversion =
            format!("|request: {request}| Ok(<D as Conversions>::{function}(request))");
        let registration = match endpoint.kind {
            Kind::Command if endpoint.custom => format!(".command(\"{name}\", {handler})"),
            Kind::Command => format!(".command(\"{name}\", {conversion})"),
            Kind::Query => format!(
                ".query(\"{name}\", {}, <D as Conversions>::{function}_response)",
                if endpoint.custom {
                    &handler
                } else {
                    &conversion
                }
            ),
            Kind::IoQuery => format!(
                ".io_query(\"{name}\", {{\nlet handlers = Arc::clone(&handlers);\nmove |request: {request}| \
                 {{\nlet handlers = Arc::clone(&handlers);\nBox::pin(async move {{ H::{function}(&handlers, \
                 request).await }})\n}}\n}})"
            ),
            Kind::State => format!(".state(\"{name}\", <D as Conversions>::{function})"),
            Kind::Event => format!(".event(\"{name}\", <D as Conversions>::{function})"),
        };
        _ = writeln!(registrations, "{registration}");
        packages.extend(
            endpoint
                .request
                .iter()
                .map(|message| message.package.clone()),
        );
        if endpoint.kind == Kind::IoQuery {
            packages.extend(endpoint.reply.iter().map(|message| message.package.clone()));
        }
    }
    let domain = domain_trait(endpoints);
    let mut imports = String::new();
    if handled
        .iter()
        .any(|endpoint| endpoint.kind == Kind::IoQuery)
    {
        imports.push_str("use core::future::Future;\n");
    }
    if !handled.is_empty() {
        imports.push_str("use std::sync::Arc;\n\n");
    }
    if !handled.is_empty() || !conversions {
        _ = writeln!(imports, "use blueos_domain::{domain};");
    }
    if !packages.is_empty() {
        _ = writeln!(
            imports,
            "use blueos_idl::msg::{{{}}};",
            packages.into_iter().collect::<Vec<_>>().join(", ")
        );
    }
    let refusal = if handled.is_empty() { "" } else { "Refusal, " };
    _ = writeln!(imports, "use blueos_service::{{{refusal}ServiceBuilder}};");
    if conversions {
        _ = writeln!(imports, "use {api_crate}::endpoints::Conversions;");
    }
    let mut source = format!(
        "//! The endpoints of the `{service}` Service, registered as `endpoints.toml` lists them.\n//!\n\
         {GENERATED_NOTICE}\n{imports}\n/// The name of the `{service}` Service, in each of its keys: \
         `blueos/v1/{service}/...`.\npub const NAME: &str = \"{service}\";\n"
    );
    let manifest_endpoints = manifest_endpoints_vec_source(endpoints, service);
    let bound = if conversions { "Conversions" } else { domain };
    let manifest_tail = format!("\n.manifest_endpoints({manifest_endpoints})");
    if handled.is_empty() {
        _ = write!(
            source,
            "\n/// Registers every endpoint of `endpoints.toml` on `builder`.\npub fn register<D: {bound}, Context>(builder: \
             ServiceBuilder<D, Context>) -> ServiceBuilder<D, Context> {{\nbuilder\n{registrations}{manifest_tail}\n}}\n"
        );
        return source;
    }
    let list = handled
        .iter()
        .map(|endpoint| format!("`{}` for the {}", endpoint.function, endpoint.title()))
        .collect::<Vec<_>>()
        .join(", ");
    _ = write!(
        source,
        "\n/// Handles the endpoints of the `{service}` Service whose mapping is not a plain conversion: the \
         `custom`\n/// Commands and Queries, and the IO queries. Implement it in `handlers.rs` and pass it to \
         [`register`].\n#[diagnostic::on_unimplemented(\nmessage = \"`{{Self}}` does not handle the custom \
         endpoints of the `{service}` Service\",\nlabel = \"no `impl Handlers<D> for {{Self}}` in the \
         `{service}` app crate\",\nnote = \"implement {list}\"\n)]\npub trait Handlers<D: {domain}>: Send + Sync + \
         'static {{\n{methods}}}\n\n/// Registers every endpoint of `endpoints.toml` on `builder`, with `handlers` \
         for the custom ones.\npub fn register<D: {bound}, H: Handlers<D>, Context>(builder: ServiceBuilder<D, \
         Context>, handlers: H) -> ServiceBuilder<D, Context> {{\nlet handlers = Arc::new(handlers);\nbuilder\n{registrations}{manifest_tail}\n}}\n"
    );
    source
}

fn manifest_endpoints_vec_source(endpoints: &[Endpoint], service: &str) -> String {
    if endpoints.is_empty() {
        return "vec![]".to_owned();
    }
    let mut rows = String::new();
    for endpoint in endpoints {
        let info = endpoint.endpoint_info(service);
        _ = writeln!(
            rows,
            "        blueos_idl::msg::blueos_msgs::EndpointInfo {{\n            kind: \"{kind}\".into(),\n            \
             name: \"{name}\".into(),\n            key: \"{key}\".into(),\n            request_schema: \
             \"{request_schema}\".into(),\n            response_schema: \"{response_schema}\".into(),\n        }},",
            kind = info.kind,
            name = info.name,
            key = info.key,
            request_schema = info.request_schema,
            response_schema = info.response_schema,
        );
    }
    format!("vec![\n{rows}    ]")
}

fn domain_trait(endpoints: &[Endpoint]) -> &'static str {
    if endpoints
        .iter()
        .any(|endpoint| endpoint.kind == Kind::Query)
    {
        "DomainQueries"
    } else {
        "Domain"
    }
}

fn typescript_client_source(service: &str, endpoints: &[Endpoint]) -> String {
    let mut key_helpers = BTreeSet::new();
    for endpoint in endpoints {
        let helper = match endpoint.kind {
            Kind::Command => "commandKey",
            Kind::Query | Kind::IoQuery => "queryKey",
            Kind::State => "stateKey",
            Kind::Event => "eventKey",
        };
        key_helpers.insert(helper);
    }
    let mut source = format!("{TYPESCRIPT_GENERATED_NOTICE}\n");
    if endpoints
        .iter()
        .any(|endpoint| endpoint.request.is_some() || endpoint.reply.is_some())
    {
        source.push_str("import type * as Idl from '@blueos-idl/messages'\n\n");
    }
    if !key_helpers.is_empty() {
        let helpers = key_helpers.into_iter().collect::<Vec<_>>().join(",\n  ");
        _ = write!(
            source,
            "import {{\n  {helpers},\n}} from '../keys'\n",
            helpers = helpers
        );
    }
    _ = write!(
        source,
        "\n/** The name of the `{service}` Service, in each of its keys: `blueos/v1/{service}/...`. */\nexport const NAME = \
         '{service}'\n"
    );
    for endpoint in endpoints {
        let name = &endpoint.name;
        let export_name = typescript_export_name(name);
        let key_helper = match endpoint.kind {
            Kind::Command => "commandKey",
            Kind::Query | Kind::IoQuery => "queryKey",
            Kind::State => "stateKey",
            Kind::Event => "eventKey",
        };
        let kind = match endpoint.kind {
            Kind::Command => "command",
            Kind::Query => "query",
            Kind::IoQuery => "io_query",
            Kind::State => "state",
            Kind::Event => "event",
        };
        let key = endpoint.key(service);
        _ = write!(
            source,
            "\n/** {kind} `{name}` at `{key}`. */\nexport const {export_name} = {{\n  kind: '{kind}' as const,\n  name: \
             '{name}',\n  key: {key_helper}(NAME, '{name}'),\n"
        );
        if let Some(request) = &endpoint.request {
            _ = writeln!(
                source,
                "  requestSchema: '{}' as const,",
                request.schema_name()
            );
        }
        if let Some(reply) = &endpoint.reply {
            let field = if endpoint.kind == Kind::State || endpoint.kind == Kind::Event {
                "messageSchema"
            } else {
                "responseSchema"
            };
            _ = writeln!(source, "  {field}: '{}' as const,", reply.schema_name());
        }
        source.push_str("}\n");
        if let Some(request) = &endpoint.request {
            _ = writeln!(
                source,
                "export type {export_name}Request = Idl.{}",
                request.typescript_type()
            );
        }
        if endpoint.kind == Kind::Query || endpoint.kind == Kind::IoQuery {
            if let Some(reply) = &endpoint.reply {
                _ = writeln!(
                    source,
                    "export type {export_name}Response = Idl.{}",
                    reply.typescript_type()
                );
            }
        } else if let Some(reply) = &endpoint.reply {
            let type_name = typescript_type_name(name);
            _ = writeln!(
                source,
                "export type {type_name} = Idl.{}",
                reply.typescript_type()
            );
        }
    }
    source
}

fn typescript_export_name(name: &str) -> String {
    name.to_owned()
}

fn typescript_type_name(name: &str) -> String {
    name.to_case(Case::UpperCamel)
}
