[package]
name = "blueos-recorder-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blueos-domain.workspace = true
blueos-idl.workspace = true
blueos-recorder-capture.workspace = true
blueos-recorder-domain.workspace = true
blueos-recorder-library.workspace = true

[lints]
workspace = true
