[package]
name = "blueos-comms"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["zenoh"]
zenoh = ["dep:blueos-comms-zenoh"]
channel = ["dep:blueos-comms-channel"]

[[test]]
name = "channel_driver"
required-features = ["channel"]

[dependencies]
async-trait.workspace = true
blueos-comms-channel = { workspace = true, optional = true }
blueos-comms-driver.workspace = true
blueos-comms-zenoh = { workspace = true, optional = true }
bytes.workspace = true
futures.workspace = true
tokio.workspace = true

[dev-dependencies]
bytes.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
