[package]
name = "blueos-comms-zenoh"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
blueos-comms-driver.workspace = true
futures.workspace = true
tokio.workspace = true
zenoh.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
