[package]
name = "blueos"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "blueos"
path = "src/main.rs"

[features]
default = ["all-services"]
all-services = ["autopilot", "calibration"]
autopilot = ["dep:autopilot"]
calibration = ["dep:calibration"]

[dependencies]
autopilot = { path = "../services/autopilot/app", optional = true }
calibration = { path = "../services/calibration/app", optional = true }
