[package]
name = "blueos-recorder-mavlink"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blueos-recorder-cameras.workspace = true
mavlink.workspace = true
mavlink-codec.workspace = true
tracing.workspace = true

[lints]
workspace = true
