[workspace]
resolver = "2"
members = [
    "libs/adapters/cli",
    "libs/adapters/comms",
    "libs/adapters/comms/channel",
    "libs/adapters/comms/driver",
    "libs/adapters/comms/zenoh",
    "libs/adapters/configs",
    "libs/adapters/logging",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.release]
lto = "thin"
panic = "unwind"
strip = true

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
json5 = "0.4"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = { version = "2", default-features = false }
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zenoh = { version = "=1.9.0", default-features = false, features = ["transport_tcp"] }
