[workspace]
resolver = "2"
members = [
    "libs/logic/smoke",
    "libs/idl",
    "libs/idl/codegen",
    "libs/tools/rust-style-check",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.release]
lto = "thin"
panic = "unwind"
strip = true

[workspace.dependencies]
blueos-idl = { path = "libs/idl" }
blueos-idl-codegen = { path = "libs/idl/codegen" }
blueos-rust-style-check = { path = "libs/tools/rust-style-check" }
blueos-smoke = { path = "libs/logic/smoke" }
convert_case = "0.8"
prettyplease = "0.2"
proc-macro2 = { version = "1", default-features = false, features = ["span-locations"] }
quote = "1"
roslibrust_codegen = { version = "0.26.0", default-features = false }
sha2 = "0.10"
syn = { version = "2", default-features = false, features = ["full", "parsing", "printing", "clone-impls", "visit"] }
walkdir = { version = "2", default-features = false }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
unreachable_pub = "deny"

[workspace.lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
alloc_instead_of_core = "deny"
arbitrary_source_item_ordering = "deny"
await_holding_lock = "deny"
clone_on_copy = "warn"
clone_on_ref_ptr = "warn"
implicit_clone = "warn"
min_ident_chars = "deny"
pub_use = "deny"
redundant_clone = "warn"
shadow_unrelated = "deny"
std_instead_of_core = "deny"
wildcard_imports = "deny"
