[package]
name = "blueos-recorder"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
blueos-api.workspace = true
blueos-comms = { workspace = true, features = ["zenoh"] }
blueos-cqrs.workspace = true
blueos-idl = { workspace = true, features = ["catalog"] }
blueos-logging.workspace = true
blueos-recorder-mcap.workspace = true
blueos-recorder-mavlink.workspace = true
blueos-recorder-policy.workspace = true
blueos-recorder-storage.workspace = true
blueos-service.workspace = true
blueos-settings.workspace = true
bytes.workspace = true
chrono.workspace = true
clap.workspace = true
futures.workspace = true
mavlink = { workspace = true, default-features = false, features = ["std", "dialect-ardupilotmega"] }
mavlink-codec.workspace = true
serde.workspace = true
serde_json.workspace = true
shellexpand = "3.1"
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time", "fs"] }
tracing.workspace = true

[dev-dependencies]
blueos-comms = { workspace = true, features = ["channel"] }
blueos-recorder-library.workspace = true
blueos-recorder-mcap.workspace = true
mcap.workspace = true
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
