[package]
name = "blueos-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blueos-domain.workspace = true
serde = { workspace = true, optional = true }
thiserror.workspace = true

[features]
serde = ["dep:serde"]

[lints]
workspace = true
