[package]
name = "blueos-comms-channel"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
blueos-comms-driver.workspace = true
tokio.workspace = true
tracing.workspace = true

