use catalog_kernel::id::journey::JourneyId;
use catalog_model::http::http_method_label;
use catalog_model::journey::HttpMethod;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProbeClass {
    B1,
    B2,
    B3,
    B4,
    B5,
    B8,
    B9,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProbeBlast {
    Safe,
    Reversible,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NegativeProbe {
    pub id: &'static str,
    pub journey_id: JourneyId,
    pub class: ProbeClass,
    pub method: HttpMethod,
    pub path: &'static str,
    pub query: Option<&'static str>,
    pub body: Option<&'static str>,
    pub expected_status: Option<u16>,
    pub blast: ProbeBlast,
}

pub const NEGATIVE_PROBES: &[NegativeProbe] = &[
    NegativeProbe {
        id: "NP-01",
        journey_id: JourneyId::RunHostCommand,
        class: ProbeClass::B2,
        method: HttpMethod::Post,
        path: "/commander/v1.0/command/host",
        query: Some("command=true&i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-02",
        journey_id: JourneyId::RebootOnboardComputer,
        class: ProbeClass::B2,
        method: HttpMethod::Post,
        path: "/commander/v1.0/shutdown",
        query: Some("shutdown_type=reboot&i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-03",
        journey_id: JourneyId::ShutdownOnboardComputer,
        class: ProbeClass::B2,
        method: HttpMethod::Post,
        path: "/commander/v1.0/shutdown",
        query: Some("shutdown_type=poweroff&i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-04",
        journey_id: JourneyId::SyncSystemTime,
        class: ProbeClass::B2,
        method: HttpMethod::Post,
        path: "/commander/v1.0/set_time",
        query: Some("unix_time_seconds=1700000000&i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-05",
        journey_id: JourneyId::ResetBlueosSettings,
        class: ProbeClass::B2,
        method: HttpMethod::Post,
        path: "/commander/v1.0/settings/reset",
        query: Some("i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-06",
        journey_id: JourneyId::InspectRaspberryEepromBootloader,
        class: ProbeClass::B2,
        method: HttpMethod::Get,
        path: "/commander/v1.0/raspi/vcgencmd",
        query: Some("command=version&i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-07",
        journey_id: JourneyId::InspectRaspberryEepromBootloader,
        class: ProbeClass::B2,
        method: HttpMethod::Get,
        path: "/commander/v1.0/raspi/eeprom_update",
        query: Some("i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-08",
        journey_id: JourneyId::UpdateRaspberryEepromBootloader,
        class: ProbeClass::B2,
        method: HttpMethod::Post,
        path: "/commander/v1.0/raspi/eeprom_update",
        query: Some("i_know_what_i_am_doing=false"),
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-09",
        journey_id: JourneyId::RunHostCommand,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/commander/v1.0/command/host",
        query: Some("i_know_what_i_am_doing=false"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-11",
        journey_id: JourneyId::RebootOnboardComputer,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/commander/v1.0/shutdown",
        query: Some("shutdown_type=banana&i_know_what_i_am_doing=false"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-12",
        journey_id: JourneyId::ChangeUiThemeColor,
        class: ProbeClass::B1,
        method: HttpMethod::Put,
        path: "/customization/v1.0/theme",
        query: None,
        body: Some(r##"{"primary":"#ZZZZZZ"}"##),
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-13",
        journey_id: JourneyId::ChangeUiThemeColor,
        class: ProbeClass::B1,
        method: HttpMethod::Put,
        path: "/customization/v1.0/theme",
        query: None,
        body: Some(r##"{"primary":"#fff"}"##),
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-14",
        journey_id: JourneyId::ChangeUiThemeColor,
        class: ProbeClass::B1,
        method: HttpMethod::Put,
        path: "/customization/v1.0/theme",
        query: None,
        body: Some("{}"),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-19",
        journey_id: JourneyId::Delete3dModelOverride,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/customization/v1.0/models/np-definitely-missing.glb",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-24",
        journey_id: JourneyId::ModifyBagDatabase,
        class: ProbeClass::B1,
        method: HttpMethod::Get,
        path: "/bag/v1.0/get/np/definitely/missing",
        query: None,
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-25",
        journey_id: JourneyId::ModifyBagDatabase,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/bag/v1.0/overwrite",
        query: Some("path=np-catalog-probe"),
        body: Some(r#"{"not":"#),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-26",
        journey_id: JourneyId::InspectDiskUsage,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/disk-usage/v1.0/disk/usage",
        query: Some("path=/np/definitely/missing"),
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-27",
        journey_id: JourneyId::InspectDiskUsage,
        class: ProbeClass::B1,
        method: HttpMethod::Get,
        path: "/disk-usage/v1.0/disk/usage",
        query: Some("path=/usr/blueos/userdata/../../../etc"),
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-28",
        journey_id: JourneyId::FreeDiskSpace,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/disk-usage/v1.0/disk/paths/etc",
        query: None,
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-29",
        journey_id: JourneyId::FreeDiskSpace,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/disk-usage/v1.0/disk/paths/usr%2Fblueos%2Fuserdata%2Fnp-no-such-file.txt",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-30",
        journey_id: JourneyId::RunSingleDiskSpeedTest,
        class: ProbeClass::B5,
        method: HttpMethod::Get,
        path: "/disk-usage/v1.0/disk/speed",
        query: Some("size_bytes=9007199254740992"),
        body: None,
        expected_status: Some(507),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-31",
        journey_id: JourneyId::ForgetSavedWifiNetwork,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/wifi-manager/v1.0/remove",
        query: Some("ssid=__np_no_such_ssid__"),
        body: None,
        // WifiManager.remove_network filters with a list comprehension, so an unknown SSID is a
        // silent no-op and main.py's `except StopIteration` -> 400 is unreachable.
        expected_status: Some(200),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-33",
        journey_id: JourneyId::ConnectToWifiNetwork,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/wifi-manager/v1.0/connect",
        query: Some("hidden=false"),
        body: Some("{}"),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-35",
        journey_id: JourneyId::ToggleHotspot,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/wifi-manager/v1.0/hotspot",
        query: Some("enable=banana"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-37",
        journey_id: JourneyId::ToggleSmartHotspot,
        class: ProbeClass::B4,
        method: HttpMethod::Post,
        path: "/wifi-manager/v1.0/smart_hotspot",
        query: Some("enable=banana"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-38",
        journey_id: JourneyId::ConnectToWifiNetwork,
        class: ProbeClass::B5,
        method: HttpMethod::Get,
        path: "/wifi-manager/v1.0/scan",
        query: None,
        body: None,
        expected_status: Some(425),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-39",
        journey_id: JourneyId::RenameVehicle,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/beacon/v1.0/vehicle_name",
        query: None,
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-41",
        journey_id: JourneyId::AssignStaticIpAddress,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/cable-guy/v1.0/address",
        query: Some("interface_name=nonexistent0"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-42",
        journey_id: JourneyId::AssignStaticIpAddress,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/cable-guy/v1.0/address",
        query: Some("interface_name=nonexistent0&ip_address=10.99.99.99"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-43",
        journey_id: JourneyId::AcquireDynamicIpAddress,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/cable-guy/v1.0/dynamic_ip",
        query: Some("interface_name=nonexistent0"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-45",
        journey_id: JourneyId::DisableOnboardDhcpServer,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/cable-guy/v1.0/dhcp",
        query: Some("interface_name=nonexistent0"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-46",
        journey_id: JourneyId::ConfigureHostDns,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/cable-guy/v1.0/host_dns",
        query: None,
        body: Some(r##"{"nameservers":"notalist","lock":false}"##),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-47",
        journey_id: JourneyId::SetNetworkInterfacePriority,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/cable-guy/v1.0/set_interfaces_priority",
        query: None,
        body: Some("{}"),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-48",
        journey_id: JourneyId::ProbeInterfaceInternetConnectivity,
        class: ProbeClass::B1,
        method: HttpMethod::Get,
        path: "/helper/v1.0/ping",
        query: None,
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-49",
        journey_id: JourneyId::ProbeInterfaceInternetConnectivity,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/helper/v1.0/ping",
        query: Some("host=np-no-such-host.invalid"),
        body: None,
        // body may contain false; status 200 is sufficient for wave-1
        expected_status: Some(200),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-51",
        journey_id: JourneyId::InstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/extension/np.no.such.extension/v0.0.0/install",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-52",
        journey_id: JourneyId::UninstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/kraken/v2.0/extension/np.no.such.extension/v0.0.0",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-53",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/extension/np.no.such.extension/restart",
        query: None,
        body: None,
        // Untagged routes go through Extension.from_running, which raises ExtensionNotRunning
        // (400) rather than ExtensionNotFound (404) for an unknown identifier.
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-54",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/container/np_no_such_container/log",
        query: Some("timeout=1"),
        body: None,
        // Pinned `2.0-dev/model` source streams 200 before ContainerNotFound. 1.4.4-beta.19+
        // (`e416aebf7`) looks up the container first and returns 404. Evaluator accepts both.
        expected_status: Some(200),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-55",
        journey_id: JourneyId::EditExtensionDevVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Put,
        path: "/kraken/v2.0/extension/np.no.such.extension/v0.0.0",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-56",
        journey_id: JourneyId::InstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/extension/np.no.such.extension/install",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-57",
        journey_id: JourneyId::EditExtensionDevVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Put,
        path: "/kraken/v2.0/extension/np.no.such.extension",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-58",
        journey_id: JourneyId::BrowseExtensionStore,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/manifest/np.no.such.manifest/details",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-50",
        journey_id: JourneyId::InstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/extension/np.no.such.extension/v0.0.0/details",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-59",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/container/extension-nosuchcontainerlifecycle/details",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-64",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/container/extension-nosuchcontainerlifecycle/stats",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-65",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/jobs/00000000-0000-4000-8000-000000000000",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-72",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/kraken/v2.0/manifest/bluerobotics-production",
        query: None,
        body: None,
        expected_status: Some(409),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-60",
        journey_id: JourneyId::SwitchLocalBlueosVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/version-chooser/v1.0/version/current",
        query: None,
        body: Some(r##"{"repository":"bluerobotics/blueos-core","tag":"np-no-such-tag"}"##),
        expected_status: Some(412),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-61",
        journey_id: JourneyId::DeleteLocalBlueosVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/version-chooser/v1.0/version/delete",
        query: None,
        body: Some(r##"{"repository":"bluerobotics/blueos-core","tag":"np-no-such-tag"}"##),
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-62",
        journey_id: JourneyId::DeleteLocalBlueosVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/version-chooser/v1.0/version/delete",
        query: None,
        body: None,
        expected_status: Some(500),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-63",
        journey_id: JourneyId::UpdateBootstrapImage,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/version-chooser/v1.0/bootstrap/current",
        query: None,
        body: Some(r##"{"tag":"np-no-such-tag"}"##),
        expected_status: Some(412),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-66",
        journey_id: JourneyId::UpdateBlueosVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/version-chooser/v1.0/version/available/bluerobotics/np-no-such-image",
        query: None,
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-67",
        journey_id: JourneyId::DownloadVideoRecording,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/recorder-extractor/v1.0/recorder/files/np-no-such.mp4",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-68",
        journey_id: JourneyId::DownloadVideoRecording,
        class: ProbeClass::B1,
        method: HttpMethod::Get,
        path: "/recorder-extractor/v1.0/recorder/files/np-bad.txt",
        query: None,
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-69",
        journey_id: JourneyId::DeleteVideoRecording,
        class: ProbeClass::B1,
        method: HttpMethod::Delete,
        path: "/recorder-extractor/v1.0/recorder/files/..%2F..%2Fetc%2Fpasswd",
        query: None,
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-70",
        journey_id: JourneyId::DeleteVideoRecording,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/recorder-extractor/v1.0/recorder/files/np-no-such.mp4",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-71",
        journey_id: JourneyId::BrowseVideoRecordings,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/recorder-extractor/v1.0/recorder/files/np-no-such.mp4/thumbnail",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-78",
        journey_id: JourneyId::RunSitlSimulation,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/ardupilot-manager/v1.0/sitl_frame",
        query: Some("frame=np_no_such_frame"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-79",
        journey_id: JourneyId::RemoveSerialBridge,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/bridget/v1.0/bridges",
        query: None,
        body: Some(
            r##"{"serial_path":"/dev/ttyNOPE","baud":115200,"ip":"127.0.0.1","udp_target_port":14559,"udp_listen_port":14558}"##,
        ),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-80",
        journey_id: JourneyId::CreateSerialToUdpBridge,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/bridget/v1.0/bridges",
        query: None,
        body: Some("{}"),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-82",
        journey_id: JourneyId::RemoveConfiguredNmeaSocket,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/nmea-injector/v1.0/socks",
        query: None,
        body: Some(r##"{"kind":"UDP","port":9999,"component_id":220}"##),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-83",
        journey_id: JourneyId::AddExternalNmeaGpsSocket,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/nmea-injector/v1.0/socks",
        query: None,
        body: Some(r##"{"kind":"BANANA","port":9999,"component_id":220}"##),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-85",
        journey_id: JourneyId::RemoveCameraStream,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/mavlink-camera-manager/delete_stream",
        query: Some("name=__np_no_such_stream__"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-89",
        journey_id: JourneyId::RunLanSpeedTest,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/network-test/post_file",
        query: None,
        body: Some(""),
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-90",
        journey_id: JourneyId::RunInternetSpeedTest,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/network-test/internet_download_speed",
        query: None,
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-96",
        journey_id: JourneyId::ModifyBagDatabase,
        class: ProbeClass::B9,
        method: HttpMethod::Get,
        path: "/bag/v1.0/get/np/definitely/missing",
        query: None,
        body: None,
        expected_status: Some(400),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-97",
        journey_id: JourneyId::InspectDiskUsage,
        class: ProbeClass::B1,
        method: HttpMethod::Get,
        path: "/disk-usage/v1.0/disk/usage",
        query: Some("path=/usr/blueos/userdata&depth=-1"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-98",
        journey_id: JourneyId::EnableLegacyCameraSupport,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/commander/v1.0/raspi_config/camera_legacy",
        query: Some("enable=banana"),
        body: None,
        expected_status: None,
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-100",
        journey_id: JourneyId::ViewCameraStreams,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/mavlink-camera-manager/v4l",
        query: None,
        body: None,
        expected_status: Some(200),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-101",
        journey_id: JourneyId::BrowseExtensionStore,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/manifest/tags/np.no.such.extension",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-102",
        journey_id: JourneyId::BrowseExtensionStore,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/manifest/tags/bluerobotics-production/np.no.such.extension/",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-103",
        journey_id: JourneyId::InstallCustomExtension,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/extension/",
        query: None,
        body: Some("{}"),
        expected_status: Some(422),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-104",
        journey_id: JourneyId::InstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Get,
        path: "/kraken/v2.0/extension/np.no.such.extension/details",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-105",
        journey_id: JourneyId::UninstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/kraken/v2.0/extension/np.no.such.extension",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-106",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/kraken/v2.0/jobs/00000000-0000-4000-8000-000000000001",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-107",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/jobs/v2.0/extension/",
        query: None,
        body: None,
        expected_status: Some(422),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-108",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/manifest/",
        query: Some("validate_url=true"),
        body: Some(r##"{"name":"np-probe","url":"http://127.0.0.1:1/no.json","enabled":false}"##),
        expected_status: Some(502),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-109",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B1,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/manifest/",
        query: Some("validate_url=true"),
        body: Some(r##"{"name":"np-probe","url":"not-a-url","enabled":false}"##),
        expected_status: Some(502),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-110",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B4,
        method: HttpMethod::Put,
        path: "/kraken/v2.0/manifest/bluerobotics-production/details",
        query: None,
        body: Some(r##"{"name":"nope"}"##),
        expected_status: Some(409),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-111",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/manifest/np-no-such-manifest/enable",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-112",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v2.0/manifest/np-no-such-manifest/disable",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-113",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Put,
        path: "/kraken/v2.0/manifest/np-no-such-manifest/details",
        query: None,
        body: Some(r##"{"name":"nope"}"##),
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-114",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Put,
        // Unknown id 404s at any order index. Factory disable/reorder are allowed (204).
        path: "/kraken/v2.0/manifest/np-no-such-manifest/order/0",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-115",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Delete,
        path: "/kraken/v2.0/manifest/np-no-such-manifest",
        query: None,
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-116",
        journey_id: JourneyId::AddCustomManifest,
        class: ProbeClass::B3,
        method: HttpMethod::Put,
        path: "/kraken/v2.0/manifest/orders",
        query: None,
        body: Some(r##"["np-no-such-manifest"]"##),
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-117",
        journey_id: JourneyId::UninstallExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v1.0/extension/uninstall",
        query: Some("extension_identifier=np.no.such.extension"),
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-118",
        journey_id: JourneyId::ConfigureInstalledExtension,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v1.0/extension/enable",
        query: Some("extension_identifier=np.no.such.extension"),
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
    NegativeProbe {
        id: "NP-119",
        journey_id: JourneyId::EditExtensionDevVersion,
        class: ProbeClass::B3,
        method: HttpMethod::Post,
        path: "/kraken/v1.0/extension/update_to_version",
        query: Some("extension_identifier=np.no.such.extension&new_version=v0.0.0"),
        body: None,
        expected_status: Some(404),
        blast: ProbeBlast::Safe,
    },
];

pub fn negative_probe_url(base: &str, probe: &NegativeProbe) -> String {
    let url = crate::runner::join_url(base, probe.path);
    match probe.query {
        Some(query) => format!("{url}?{query}"),
        None => url,
    }
}

/// Kraken nginx probes used by `--extension-lifecycle` (skips unasserted rows at the call site).
/// NP-101/NP-102/NP-108 have named recs in phase_issue_contracts; omit them here to avoid doubles.
pub fn kraken_lifecycle_probes() -> impl Iterator<Item = &'static NegativeProbe> {
    NEGATIVE_PROBES.iter().filter(|probe| {
        probe.path.starts_with("/kraken/") && !matches!(probe.id, "NP-101" | "NP-102" | "NP-108")
    })
}

pub fn format_negative_dry_run(probe: &NegativeProbe, url: &str) -> String {
    format!(
        "DRY-RUN {} {} {} → {url}",
        probe.id,
        http_method_label(&probe.method),
        probe.path
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn negative_probe_ids_are_unique() {
        let mut seen = HashSet::new();
        for probe in NEGATIVE_PROBES {
            assert!(seen.insert(probe.id), "duplicate probe id {}", probe.id);
        }
    }

    #[test]
    fn every_negative_probe_path_starts_with_slash() {
        for probe in NEGATIVE_PROBES {
            assert!(
                probe.path.starts_with('/'),
                "{} path must start with /: {}",
                probe.id,
                probe.path
            );
        }
    }

    #[test]
    fn np04_query_contains_far_past_timestamp() {
        let np04 = NEGATIVE_PROBES
            .iter()
            .find(|probe| probe.id == "NP-04")
            .expect("NP-04");
        let query = np04.query.expect("NP-04 query");
        assert!(
            query.contains("1700000000"),
            "NP-04 must use unix_time_seconds=1700000000: {query}"
        );
    }
}
