[package]
name = "blueos_service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
blueos-api.workspace = true
blueos_cli = { path = "../../adapters/cli" }
blueos_comms = { path = "../../adapters/comms", default-features = false, features = ["zenoh", "channel"] }
blueos_cqrs = { path = "../../logic/cqrs" }
blueos-idl.workspace = true
blueos_jobs = { path = "../../logic/jobs" }
blueos_logging = { path = "../../adapters/logging" }
blueos_settings = { path = "../../adapters/settings" }
bytes.workspace = true
futures.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time", "macros"] }
tracing.workspace = true

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile = "3"
tokio = { workspace = true, features = ["test-util"] }
