[package]
name = "blueos-service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
blueos-api.workspace = true
blueos-cli.workspace = true
blueos-comms = { workspace = true, features = ["zenoh"] }
blueos-cqrs.workspace = true
blueos-idl.workspace = true
blueos-jobs.workspace = true
blueos-logging.workspace = true
blueos-settings.workspace = true
bytes.workspace = true
futures.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time", "macros", "signal"] }
tracing.workspace = true

[dev-dependencies]
blueos-comms = { workspace = true, features = ["channel"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile = "3"
tokio = { workspace = true, features = ["test-util"] }
