PHASE_IDLE = "idle"
PHASE_ONE_STREAM_REDIRECTED = "one_stream_redirected"
PHASE_ARMED_MAVLINK_ONLY = "armed_mavlink_only"
PHASE_ONE_STREAM_RECORDING = "one_stream_recording"
PHASE_TWO_STREAMS_RECORDING = "two_streams_recording"

LOAD_SCENARIO_PHASES = (
    PHASE_IDLE,
    PHASE_ONE_STREAM_REDIRECTED,
    PHASE_ARMED_MAVLINK_ONLY,
    PHASE_ONE_STREAM_RECORDING,
    PHASE_TWO_STREAMS_RECORDING,
)

PHASE_DURATION_SECONDS = 60.0
SAMPLE_INTERVAL_SECONDS = 1.0
MIN_RUNS_PER_BINARY = 10
RESULT_SCHEMA_VERSION = 2

CLIP_DURATION_SECONDS = 5.0
CLIP_FRAME_RATE = 30.0
CLIP_BITRATE_BITS_PER_SECOND = 50_000_000

DEVICE_RECORDINGS_DIRECTORY = "/usr/blueos/userdata/recorder"
ACTIVE_RECORDING_FILE_NAME = "live.mcap"

PROCESS_RECORDER = "recorder"
PROCESS_MAVLINK_CAMERA_MANAGER = "mavlink_camera_manager"
PROCESS_ZENOH_ROUTER = "zenohd"
PROCESS_SYSTEM = "system"

MONITORED_PROCESSES = (
    PROCESS_RECORDER,
    PROCESS_MAVLINK_CAMERA_MANAGER,
    PROCESS_ZENOH_ROUTER,
    PROCESS_SYSTEM,
)
