PHASE_ONE_STREAM_REDIRECTED = "one_stream_redirected"
PHASE_DURATION_SECONDS = 60.0
SAMPLE_INTERVAL_SECONDS = 1.0
RESULT_SCHEMA_VERSION = 1

PROCESS_RECORDER = "recorder"
PROCESS_MAVLINK_CAMERA_MANAGER = "mavlink_camera_manager"
PROCESS_ZENOH_ROUTER = "zenohd"
PROCESS_SYSTEM = "system"

MONITORED_PROCESSES = (
    PROCESS_RECORDER,
    PROCESS_MAVLINK_CAMERA_MANAGER,
    PROCESS_ZENOH_ROUTER,
    PROCESS_SYSTEM,
)
