[package]
name = "blueos-recorder-mcap"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
blueos-comms = { workspace = true, features = ["zenoh"] }
clap = { workspace = true, features = ["derive"] }
json5.workspace = true
mcap.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
bytes.workspace = true
tempfile = "3"
