[workspace]
resolver = "2"
members = [
    "app",
    "services/autopilot/app",
    "services/autopilot/logic/preflight",
    "services/calibration/app",
    "services/calibration/logic/sensors",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.release]
lto = "thin"
panic = "unwind"
strip = true

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
