//! Generates each Service's endpoint registration from its endpoint manifest (D-26).

#![expect(
    clippy::arbitrary_source_item_ordering,
    reason = "types must load before discover and emit, which import manifest types"
)]

use std::{io, path::PathBuf};

mod endpoint_methods;
mod kind_labels;
mod types;

mod discover;
mod emit;
mod generate;

/// The file name of an endpoint manifest, next to the `Cargo.toml` of a Service's app crate.
pub const MANIFEST_FILE: &str = "endpoints.toml";

/// Where the TypeScript clients are committed, under `core/`.
pub(crate) const TYPESCRIPT_DIR: &str = "frontend/src/libs/blueos-api/services";

/// The endpoints D-12 gives every Service. A manifest cannot reuse their names, and `api.lock` records them for
/// every Service.
// ponytail: records `settings` and `UpdateSettings` for every Service, as the generator cannot see a
// `ServiceBuilder::settings` opt-in; a manifest field would make the lock exact.
// A Job control names its Job in the attachment, so a body is needed only to answer a permission request.
pub(crate) const STANDARD_ENDPOINTS: [StandardEndpoint; 11] = [
    StandardEndpoint {
        name: "info",
        key: "query/info",
        interface_type: "blueos_msgs/msg/ServiceInfo",
    },
    StandardEndpoint {
        name: "status",
        key: "state/status",
        interface_type: "blueos_msgs/msg/ServiceStatus",
    },
    StandardEndpoint {
        name: "settings",
        key: "settings",
        interface_type: "blueos_msgs/msg/SettingsEnvelope",
    },
    StandardEndpoint {
        name: "UpdateSettings",
        key: "command/UpdateSettings",
        interface_type: "blueos_msgs/action/UpdateSettings",
    },
    StandardEndpoint {
        name: "log",
        key: "log",
        interface_type: "foxglove_msgs/msg/Log",
    },
    StandardEndpoint {
        name: "metrics",
        key: "state/metrics",
        interface_type: "blueos_msgs/msg/ServiceMetrics",
    },
    StandardEndpoint {
        name: "jobs",
        key: "jobs",
        interface_type: "blueos_msgs/msg/JobList",
    },
    StandardEndpoint {
        name: "CancelJob",
        key: "command/CancelJob",
        interface_type: "std_msgs/msg/Empty",
    },
    StandardEndpoint {
        name: "PauseJob",
        key: "command/PauseJob",
        interface_type: "std_msgs/msg/Empty",
    },
    StandardEndpoint {
        name: "ResumeJob",
        key: "command/ResumeJob",
        interface_type: "std_msgs/msg/Empty",
    },
    StandardEndpoint {
        name: "AnswerPermission",
        key: "command/AnswerPermission",
        interface_type: "blueos_msgs/msg/PermissionAnswer",
    },
];

pub(crate) const GENERATED_NOTICE: &str = "//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not \
                                edit it: change\n//! the manifest and run `cargo run -p blueos-idl-codegen -- \
                                --write` in `core/`.\n";

pub(crate) const TYPESCRIPT_GENERATED_NOTICE: &str = "// Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. \
                                          Do not edit: change\n// the manifest and run `cargo run -p blueos-idl-codegen -- \
                                          --write` in `core/`.\n";

/// Why the generator could not generate the endpoint files of the workspace.
#[derive(Debug, thiserror::Error)]
pub enum EndpointsError {
    /// A file could not be read.
    #[error("{}: {error}", path.display())]
    Read {
        /// The file.
        path: PathBuf,
        /// Why it could not be read.
        error: io::Error,
    },
    /// A `Cargo.toml` does not parse, or misses the field the generator needs.
    #[error("{}: {reason}", path.display())]
    Cargo {
        /// The `Cargo.toml`.
        path: PathBuf,
        /// What is wrong with it.
        reason: String,
    },
    /// An endpoint manifest is wrong.
    #[error("{}: {error}", path.display())]
    Manifest {
        /// The manifest.
        path: PathBuf,
        /// What is wrong with it.
        error: ManifestError,
    },
    /// `rustfmt` could not format generated endpoint Rust.
    #[error("rustfmt failed on generated endpoints: {reason}")]
    Rustfmt {
        /// Why formatting failed.
        reason: String,
    },
}

/// What is wrong with an endpoint manifest.
#[derive(Debug, PartialEq, Eq, thiserror::Error)]
pub enum ManifestError {
    /// The manifest is not valid TOML, or has a field the format does not have.
    #[error("the manifest does not parse: {0}")]
    Parse(String),
    /// A Service or endpoint name is not a plain identifier.
    #[error(
        "`{0}` is not a valid name: use ASCII letters, digits and `_`, start with a letter, and avoid Rust keywords"
    )]
    InvalidName(String),
    /// An endpoint uses a name every Service already has (D-12).
    #[error("the endpoint `{0}` uses a name every Service already has (D-12)")]
    Reserved(String),
    /// Two endpoints generate the same function.
    #[error(
        "the endpoints `{first}` and `{second}` both generate `{function}`: endpoint names are unique in a Service"
    )]
    Duplicate {
        /// The endpoint listed first.
        first: String,
        /// The endpoint listed second.
        second: String,
        /// The function both generate.
        function: String,
    },
    /// An endpoint's type is not an interface of its kind in `core/libs/idl/interfaces`.
    #[error(
        "the endpoint `{endpoint}` has the type `{interface_type}`, which is not a `{expected}` of `blueos-idl`"
    )]
    UnknownType {
        /// The endpoint.
        endpoint: String,
        /// The type it gave.
        interface_type: String,
        /// The interface its kind needs: `.action` for a Job type, `.srv` for a Query, `.msg` for a State or an
        /// Event.
        expected: &'static str,
    },
}

/// A generated file and what it should contain.
#[derive(Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Where the file is committed.
    pub path: PathBuf,
    /// Its formatted text.
    pub contents: String,
}

/// The generated sources of one manifest, before formatting.
#[derive(Debug)]
pub struct Generated {
    /// The Service name from the manifest.
    pub service: String,
    /// `logic/api/src/endpoints.rs`: the `Conversions` trait.
    pub api: String,
    /// `app/src/endpoints.rs`: `NAME`, the `Handlers` trait and `register`.
    pub app: String,
    /// `frontend/src/libs/blueos-api/services/<service>.ts`: keys and Message types (D-14).
    pub typescript: String,
}

pub use discover::collect_endpoint_lock_lines;
pub use discover::format::format;
pub use generate::{generate, generate_all, stray_files};

pub(crate) use types::{Endpoint, InterfaceType, Kind, Manifest, StandardEndpoint};
