[package]
name = "blueos-recorder-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
blueos-recorder-mcap.workspace = true
thiserror.workspace = true
tracing.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
