//! The endpoints of the `recorder` Service, registered as `endpoints.toml` lists them.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use std::sync::Arc;

use blueos_domain::Domain;
use blueos_idl::msg::blueos_recorder_msgs;
use blueos_recorder_api::endpoints::Conversions;
use blueos_service::{Refusal, ServiceBuilder};

/// The name of the `recorder` Service, in each of its keys: `blueos/v1/recorder/...`.
pub const NAME: &str = "recorder";

/// Handles the endpoints of the `recorder` Service whose mapping is not a plain conversion: the `custom`
/// Commands and Queries, and the IO queries. Implement it in `handlers.rs` and pass it to [`register`].
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not handle the custom endpoints of the `recorder` Service",
    label = "no `impl Handlers<D> for {Self}` in the `recorder` app crate",
    note = "implement `delete_recording` for the Command `DeleteRecording`"
)]
pub trait Handlers<D: Domain>: Send + Sync + 'static {
    /// The Command `DeleteRecording`, at `blueos/v1/recorder/command/DeleteRecording`.
    ///
    /// The Domain's Request for the Message, or why it is refused.
    fn delete_recording(
        &self,
        request: blueos_recorder_msgs::DeleteRecordingCommand,
    ) -> Result<D::Request, Refusal>;
}

/// Registers every endpoint of `endpoints.toml` on `builder`, with `handlers` for the custom ones.
pub fn register<D: Conversions, H: Handlers<D>, Context>(
    builder: ServiceBuilder<D, Context>,
    handlers: H,
) -> ServiceBuilder<D, Context> {
    let handlers = Arc::new(handlers);
    builder
        .command("DeleteRecording", {
            let handlers = Arc::clone(&handlers);
            move |request: blueos_recorder_msgs::DeleteRecordingCommand| {
                H::delete_recording(&handlers, request)
            }
        })
        .command(
            "Start",
            |request: blueos_recorder_msgs::StartRecordingCommand| {
                Ok(<D as Conversions>::start(request))
            },
        )
        .command(
            "Stop",
            |request: blueos_recorder_msgs::StopRecordingCommand| {
                Ok(<D as Conversions>::stop(request))
            },
        )
        .state("library", <D as Conversions>::library)
        .state("recording", <D as Conversions>::recording)
        .manifest_endpoints(vec![
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "DeleteRecording".into(),
                key: "blueos/v1/recorder/command/DeleteRecording".into(),
                request_schema: "blueos_recorder_msgs/msg/DeleteRecordingCommand".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "Start".into(),
                key: "blueos/v1/recorder/command/Start".into(),
                request_schema: "blueos_recorder_msgs/msg/StartRecordingCommand".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "Stop".into(),
                key: "blueos/v1/recorder/command/Stop".into(),
                request_schema: "blueos_recorder_msgs/msg/StopRecordingCommand".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "library".into(),
                key: "blueos/v1/recorder/state/library".into(),
                request_schema: "".into(),
                response_schema: "blueos_recorder_msgs/msg/RecordingLibrary".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "recording".into(),
                key: "blueos/v1/recorder/state/recording".into(),
                request_schema: "".into(),
                response_schema: "blueos_recorder_msgs/msg/RecordingState".into(),
            },
        ])
}
