//! The endpoints of the `recorder` Service, registered as `endpoints.toml` lists them.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use core::future::Future;
use std::sync::Arc;

use blueos_domain::Domain;
use blueos_idl::msg::blueos_recorder_msgs;
use blueos_jobs::{DomainJobs, JobId, JobNature};
use blueos_recorder_api::endpoints::Conversions;
use blueos_service::{Refusal, ServiceBuilder};

/// The name of the `recorder` Service, in each of its keys: `blueos/v1/recorder/...`.
pub const NAME: &str = "recorder";

/// Handles the endpoints of the `recorder` Service whose mapping is not a plain conversion: the `custom`
/// Job types and the IO queries. Implement it in `handlers.rs` and pass it to [`register`].
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not handle the custom endpoints of the `recorder` Service",
    label = "no `impl Handlers<D> for {Self}` in the `recorder` app crate",
    note = "implement `delete_recording` for the Job type `DeleteRecording`, `repair_recording` for the Job type `RepairRecording`, `snapshot_recording` for the Job type `SnapshotRecording`, `index` for the IO query `index`"
)]
pub trait Handlers<D: Domain>: Send + Sync + 'static {
    /// The Job type `DeleteRecording`, at `blueos/v1/recorder/command/DeleteRecording`.
    ///
    /// The Domain's Request for the Goal, or why it is refused.
    fn delete_recording(
        &self,
        goal: blueos_recorder_msgs::DeleteRecordingGoal,
    ) -> Result<D::Request, Refusal>;

    /// The Job type `RepairRecording`, at `blueos/v1/recorder/command/RepairRecording`.
    ///
    /// The Domain's Request for the Goal, or why it is refused.
    fn repair_recording(
        &self,
        job_id: JobId,
        goal: blueos_recorder_msgs::RepairRecordingGoal,
    ) -> Result<D::Request, Refusal>;

    /// The Job type `SnapshotRecording`, at `blueos/v1/recorder/command/SnapshotRecording`.
    ///
    /// The Domain's Request for the Goal, or why it is refused.
    fn snapshot_recording(
        &self,
        goal: blueos_recorder_msgs::SnapshotRecordingGoal,
    ) -> Result<D::Request, Refusal>;

    /// The IO query `index`, at `blueos/v1/recorder/query/index`.
    ///
    /// Its response, read outside the Inbox, or why it is refused.
    fn index(
        &self,
        request: blueos_recorder_msgs::RecordingIndexRequest,
    ) -> impl Future<Output = Result<blueos_recorder_msgs::RecordingIndexResponse, Refusal>> + Send;
}

/// Registers every endpoint of `endpoints.toml` on `builder`, with `handlers` for the custom ones.
pub fn register<D: Conversions + DomainJobs, H: Handlers<D>, Context>(
    builder: ServiceBuilder<D, Context>,
    handlers: H,
) -> ServiceBuilder<D, Context> {
    let handlers = Arc::new(handlers);
    builder
        .command("DeleteRecording", {
            let handlers = Arc::clone(&handlers);
            move |goal: blueos_recorder_msgs::DeleteRecordingGoal| {
                H::delete_recording(&handlers, goal)
            }
        })
        .job_feedback(
            "DeleteRecording",
            <D as Conversions>::delete_recording_feedback,
        )
        .job_result(
            "DeleteRecording",
            <D as Conversions>::delete_recording_result,
        )
        .job(
            "RepairRecording",
            JobNature {
                lasting: true,
                cancellable: true,
                pausable: false,
                needs_permission: false,
            },
            {
                let handlers = Arc::clone(&handlers);
                move |job_id, goal: blueos_recorder_msgs::RepairRecordingGoal| {
                    H::repair_recording(&handlers, job_id, goal)
                }
            },
        )
        .job_feedback(
            "RepairRecording",
            <D as Conversions>::repair_recording_feedback,
        )
        .job_result(
            "RepairRecording",
            <D as Conversions>::repair_recording_result,
        )
        .command("SnapshotRecording", {
            let handlers = Arc::clone(&handlers);
            move |goal: blueos_recorder_msgs::SnapshotRecordingGoal| {
                H::snapshot_recording(&handlers, goal)
            }
        })
        .job_feedback(
            "SnapshotRecording",
            <D as Conversions>::snapshot_recording_feedback,
        )
        .job_result(
            "SnapshotRecording",
            <D as Conversions>::snapshot_recording_result,
        )
        .command("Start", |goal: blueos_recorder_msgs::StartRecordingGoal| {
            <D as Conversions>::start(goal).map_err(Refusal::from)
        })
        .job_feedback("Start", <D as Conversions>::start_feedback)
        .job_result("Start", <D as Conversions>::start_result)
        .command("Stop", |goal: blueos_recorder_msgs::StopRecordingGoal| {
            <D as Conversions>::stop(goal).map_err(Refusal::from)
        })
        .job_feedback("Stop", <D as Conversions>::stop_feedback)
        .job_result("Stop", <D as Conversions>::stop_result)
        .io_query("index", {
            let handlers = Arc::clone(&handlers);
            move |request: blueos_recorder_msgs::RecordingIndexRequest| {
                let handlers = Arc::clone(&handlers);
                Box::pin(async move { H::index(&handlers, request).await })
            }
        })
        .state("library", <D as Conversions>::library)
        .state("recording", <D as Conversions>::recording)
        .event("operation", <D as Conversions>::operation)
        .manifest_endpoints(vec![
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "job".into(),
                name: "DeleteRecording".into(),
                key: "blueos/v1/recorder/command/DeleteRecording".into(),
                interface_type: "blueos_recorder_msgs/action/DeleteRecording".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/action/DeleteRecording")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "job".into(),
                name: "RepairRecording".into(),
                key: "blueos/v1/recorder/command/RepairRecording".into(),
                interface_type: "blueos_recorder_msgs/action/RepairRecording".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/action/RepairRecording")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "job".into(),
                name: "SnapshotRecording".into(),
                key: "blueos/v1/recorder/command/SnapshotRecording".into(),
                interface_type: "blueos_recorder_msgs/action/SnapshotRecording".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/action/SnapshotRecording")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "job".into(),
                name: "Start".into(),
                key: "blueos/v1/recorder/command/Start".into(),
                interface_type: "blueos_recorder_msgs/action/StartRecording".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/action/StartRecording")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "job".into(),
                name: "Stop".into(),
                key: "blueos/v1/recorder/command/Stop".into(),
                interface_type: "blueos_recorder_msgs/action/StopRecording".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/action/StopRecording")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "query".into(),
                name: "index".into(),
                key: "blueos/v1/recorder/query/index".into(),
                interface_type: "blueos_recorder_msgs/srv/RecordingIndex".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/srv/RecordingIndex")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "library".into(),
                key: "blueos/v1/recorder/state/library".into(),
                interface_type: "blueos_recorder_msgs/msg/RecordingLibrary".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/msg/RecordingLibrary")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "recording".into(),
                key: "blueos/v1/recorder/state/recording".into(),
                interface_type: "blueos_recorder_msgs/msg/RecordingState".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/msg/RecordingState")
                    .unwrap_or_default()
                    .into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "event".into(),
                name: "operation".into(),
                key: "blueos/v1/recorder/event/operation".into(),
                interface_type: "blueos_recorder_msgs/msg/RecordingOperation".into(),
                schema: blueos_idl::schema("blueos_recorder_msgs/msg/RecordingOperation")
                    .unwrap_or_default()
                    .into(),
            },
        ])
}
