//! The endpoints of the `recorder` Service, registered as `endpoints.toml` lists them.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use blueos_idl::msg::blueos_recorder_msgs;
use blueos_recorder_api::endpoints::Conversions;
use blueos_service::ServiceBuilder;

/// The name of the `recorder` Service, in each of its keys: `blueos/v1/recorder/...`.
pub const NAME: &str = "recorder";

/// Registers every endpoint of `endpoints.toml` on `builder`.
pub fn register<D: Conversions, Context>(
    builder: ServiceBuilder<D, Context>,
) -> ServiceBuilder<D, Context> {
    builder
        .command(
            "Start",
            |request: blueos_recorder_msgs::StartRecordingCommand| {
                Ok(<D as Conversions>::start(request))
            },
        )
        .command(
            "Stop",
            |request: blueos_recorder_msgs::StopRecordingCommand| {
                Ok(<D as Conversions>::stop(request))
            },
        )
        .state("recording", <D as Conversions>::recording)
        .manifest_endpoints(vec![
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "Start".into(),
                key: "blueos/v1/recorder/command/Start".into(),
                request_schema: "blueos_recorder_msgs/msg/StartRecordingCommand".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "Stop".into(),
                key: "blueos/v1/recorder/command/Stop".into(),
                request_schema: "blueos_recorder_msgs/msg/StopRecordingCommand".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "recording".into(),
                key: "blueos/v1/recorder/state/recording".into(),
                request_schema: "".into(),
                response_schema: "blueos_recorder_msgs/msg/RecordingState".into(),
            },
        ])
}
