//! The endpoints of the `example` Service, registered as `endpoints.toml` lists them.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use std::sync::Arc;

use blueos_domain::Domain;
use blueos_example_api::endpoints::Conversions;
use blueos_idl::msg::blueos_example_msgs;
use blueos_jobs::{DomainJobs, JobId, JobNature};
use blueos_service::{Refusal, ServiceBuilder};

/// The name of the `example` Service, in each of its keys: `blueos/v1/example/...`.
pub const NAME: &str = "example";

/// Handles the endpoints of the `example` Service whose mapping is not a plain conversion: the `custom`
/// Job types and the IO queries. Implement it in `handlers.rs` and pass it to [`register`].
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not handle the custom endpoints of the `example` Service",
    label = "no `impl Handlers<D> for {Self}` in the `example` app crate",
    note = "implement `set_level` for the Job type `SetLevel`"
)]
pub trait Handlers<D: Domain>: Send + Sync + 'static {
    /// The Job type `SetLevel`, at `blueos/v1/example/command/SetLevel`.
    ///
    /// The Domain's Request for the Goal, or why it is refused.
    fn set_level(
        &self,
        job_id: JobId,
        goal: blueos_example_msgs::SetLevelGoal,
    ) -> Result<D::Request, Refusal>;
}

/// Registers every endpoint of `endpoints.toml` on `builder`, with `handlers` for the custom ones.
pub fn register<D: Conversions + DomainJobs, H: Handlers<D>, Context>(
    builder: ServiceBuilder<D, Context>,
    handlers: H,
) -> ServiceBuilder<D, Context> {
    let handlers = Arc::new(handlers);
    builder
        .job(
            "SetLevel",
            JobNature {
                lasting: true,
                cancellable: false,
                pausable: false,
                needs_permission: false,
            },
            {
                let handlers = Arc::clone(&handlers);
                move |job_id, goal: blueos_example_msgs::SetLevelGoal| {
                    H::set_level(&handlers, job_id, goal)
                }
            },
        )
        .job_feedback("SetLevel", <D as Conversions>::set_level_feedback)
        .job_result("SetLevel", <D as Conversions>::set_level_result)
        .manifest_endpoints(vec![blueos_idl::msg::blueos_msgs::EndpointInfo {
            kind: "job".into(),
            name: "SetLevel".into(),
            key: "blueos/v1/example/command/SetLevel".into(),
            interface_type: "blueos_example_msgs/action/SetLevel".into(),
            schema: blueos_idl::schema("blueos_example_msgs/action/SetLevel")
                .unwrap_or_default()
                .into(),
        }])
}
