[package]
name = "blueos-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
proptest.workspace = true
proptest-state-machine.workspace = true

[package.metadata.proptest]
regressions = "proptest-regressions"
