//! The endpoints of the `example` Service, registered as `endpoints.toml` lists them.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use blueos_example_api::endpoints::Conversions;
use blueos_idl::msg::blueos_example_msgs;
use blueos_service::ServiceBuilder;

/// The name of the `example` Service, in each of its keys: `blueos/v1/example/...`.
pub const NAME: &str = "example";

/// Registers every endpoint of `endpoints.toml` on `builder`.
pub fn register<D: Conversions, Context>(
    builder: ServiceBuilder<D, Context>,
) -> ServiceBuilder<D, Context> {
    builder
        .command(
            "SetLevel",
            |request: blueos_example_msgs::SetLevelRequest| {
                Ok(<D as Conversions>::set_level(request))
            },
        )
        .query(
            "Level",
            |request: blueos_example_msgs::EmptyRequest| Ok(<D as Conversions>::level(request)),
            <D as Conversions>::level_response,
        )
        .state("pump", <D as Conversions>::pump)
        .manifest_endpoints(vec![
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "command".into(),
                name: "SetLevel".into(),
                key: "blueos/v1/example/command/SetLevel".into(),
                request_schema: "blueos_example_msgs/msg/SetLevelRequest".into(),
                response_schema: "blueos_msgs/msg/CommandAck".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "query".into(),
                name: "Level".into(),
                key: "blueos/v1/example/query/Level".into(),
                request_schema: "blueos_example_msgs/msg/EmptyRequest".into(),
                response_schema: "blueos_example_msgs/msg/LevelQueryResponse".into(),
            },
            blueos_idl::msg::blueos_msgs::EndpointInfo {
                kind: "state".into(),
                name: "pump".into(),
                key: "blueos/v1/example/state/pump".into(),
                request_schema: "".into(),
                response_schema: "blueos_example_msgs/msg/PumpState".into(),
            },
        ])
}
