//! The conversions between the Messages and the Domain of the `tank` Service, one function per endpoint.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use blueos_domain::DomainQueries;
use blueos_idl::msg::blueos_example_msgs;

/// Converts between the Domain and the Messages of every endpoint of the `tank` Service that is not
/// `custom`. Implement it for the Domain in this crate: `register` in the app crate calls it.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not convert the endpoints of the `tank` Service",
    label = "no `impl Conversions for {Self}` in the `tank` logic/api crate",
    note = "implement `drain` for the Command `Drain`, `level` for the Query `Level`, `level_response` for the Query `Level`, `level_after_fill_response` for the Query `LevelAfterFill`, `tank` for the State `tank`, `level_changed` for the Event `LevelChanged`"
)]
pub trait Conversions: DomainQueries {
    /// The Command `Drain`, at `blueos/v1/tank/command/Drain`.
    ///
    /// The Domain's Request for the Message.
    fn drain(request: blueos_example_msgs::EmptyRequest) -> Self::Request;

    /// The Query `Level`, at `blueos/v1/tank/query/Level`.
    ///
    /// The Domain's Query for the Message.
    fn level(request: blueos_example_msgs::EmptyRequest) -> Self::Query;

    /// The reply of the Query `Level`.
    ///
    /// The Message for `response`, or `None` when `response` answers another Query.
    fn level_response(response: Self::Response) -> Option<blueos_example_msgs::LevelQueryResponse>;

    /// The reply of the Query `LevelAfterFill`.
    ///
    /// The Message for `response`, or `None` when `response` answers another Query.
    fn level_after_fill_response(
        response: Self::Response,
    ) -> Option<blueos_example_msgs::LevelQueryResponse>;

    /// The State `tank`, at `blueos/v1/tank/state/tank`.
    ///
    /// Its value for `snapshot`.
    fn tank(snapshot: &Self::Snapshot) -> blueos_example_msgs::LevelQueryResponse;

    /// The Event `LevelChanged`, at `blueos/v1/tank/event/LevelChanged`.
    ///
    /// What it publishes for `event`, or `None` when `event` is another one.
    fn level_changed(event: &Self::Event) -> Option<blueos_example_msgs::LevelQueryResponse>;
}
