//! The conversions between the Messages and the Domain of the `example` Service, one function per endpoint.
//!
//! Generated by `blueos-idl-codegen` from `endpoints.toml` in the app crate. Do not edit it: change
//! the manifest and run `cargo run -p blueos-idl-codegen -- --write` in `core/`.

use blueos_domain::DomainQueries;
use blueos_idl::msg::blueos_example_msgs;

/// Converts between the Domain and the Messages of every endpoint of the `example` Service that is not
/// `custom`. Implement it for the Domain in this crate: `register` in the app crate calls it.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not convert the endpoints of the `example` Service",
    label = "no `impl Conversions for {Self}` in the `example` logic/api crate",
    note = "implement `set_level` for the Command `SetLevel`, `level` for the Query `Level`, `level_response` for the Query `Level`, `pump` for the State `pump`"
)]
pub trait Conversions: DomainQueries {
    /// The Command `SetLevel`, at `blueos/v1/example/command/SetLevel`.
    ///
    /// The Domain's Request for the Message.
    fn set_level(request: blueos_example_msgs::SetLevelRequest) -> Self::Request;

    /// The Query `Level`, at `blueos/v1/example/query/Level`.
    ///
    /// The Domain's Query for the Message.
    fn level(request: blueos_example_msgs::EmptyRequest) -> Self::Query;

    /// The reply of the Query `Level`.
    ///
    /// The Message for `response`, or `None` when `response` answers another Query.
    fn level_response(response: Self::Response) -> Option<blueos_example_msgs::LevelQueryResponse>;

    /// The State `pump`, at `blueos/v1/example/state/pump`.
    ///
    /// Its value for `snapshot`.
    fn pump(snapshot: &Self::Snapshot) -> blueos_example_msgs::PumpState;
}
