#!/usr/bin/env bash
# Report D-31 ergonomics measures (goals, never gates). Usage: ergonomics_report.sh <repository_root>
#
# Measure definitions (aligned with docs/architecture/draft-1/rust-service-ergonomics-review.md P5):
#
# - Concepts per Command: lines in core/ergonomics/d31-example-command-concepts.txt (non-comment).
# - Wiring lines per endpoint: hand-edited lines a developer types to wire one public endpoint,
#   excluding generated endpoint registration (app/src/endpoints.rs, logic/api/src/endpoints.rs).
#   Per endpoint: the manifest table row, the Conversions impl methods in logic/api/src/lib.rs,
#   and Domain wiring (Request/Query variant plus the matching handle or query arm). Reported
#   value is the maximum over endpoints in example-minimal (same spirit as the review's SetLevel
#   end-to-end W sample).
# - Smallest complete Service: hand-written lines in example-minimal crates only
#   (services/example/logic/domain, logic/api, app): every .rs and Cargo.toml, plus app/endpoints.toml.
#   Excludes generated IDL files, app/tests/, and any #[cfg(test)] module at the bottom of a .rs file.
#   Matches the review's "service floor" (hand-written lines, manifests included; not cookbook/tests).
# - Framework lines to read first: fixed draft-2 read set under core/libs/.
# - Files touched per Command: distinct hand-written service files mentioning the sample Command
#   name (SetLevel); goal not set in D-31 yet.

set -euo pipefail

repository_root=${1:?repository root required}
workspace_dir="$repository_root/core"
example_dir="$workspace_dir/services/example"
concepts_file="$workspace_dir/ergonomics/d31-example-command-concepts.txt"
endpoints_manifest="$example_dir/app/endpoints.toml"
domain_lib="$example_dir/logic/domain/src/lib.rs"
api_lib="$example_dir/logic/api/src/lib.rs"

readonly -a framework_read_set=(
    "$workspace_dir/libs/logic/domain/src/lib.rs"
    "$workspace_dir/libs/logic/jobs/src/lib.rs"
    "$workspace_dir/libs/app/service/src/builder.rs"
    "$workspace_dir/libs/app/service/src/kernel/mod.rs"
    "$workspace_dir/libs/app/service/src/entry/run.rs"
)

readonly -a example_minimal_roots=(
    "$example_dir/logic/domain"
    "$example_dir/logic/api"
    "$example_dir/app"
)

is_generated() {
    local path=$1
    # shellcheck disable=SC2016
    grep -Fq 'Generated by `blueos-idl-codegen`' "$path" 2>/dev/null
}

count_production_lines() {
    local path=$1
    awk '
        /^[[:space:]]*#\[cfg\(test\)\]/ { exit }
        { count++ }
        END { print count + 0 }
    ' "$path"
}

count_hand_written_service_lines() {
    local root path line_count=0 relative
    for root in "${example_minimal_roots[@]}"; do
        [ -d "$root" ] || continue
        while IFS= read -r -d '' path; do
            relative=${path#"$example_dir/"}
            if [[ $relative == app/tests/* ]]; then
                continue
            fi
            if is_generated "$path"; then
                continue
            fi
            case "$path" in
                *.rs) line_count=$((line_count + $(count_production_lines "$path"))) ;;
                */Cargo.toml) line_count=$((line_count + $(wc -l <"$path"))) ;;
                */endpoints.toml) line_count=$((line_count + $(wc -l <"$path"))) ;;
            esac
        done < <(find "$root" \( -name '*.rs' -o -name 'Cargo.toml' -o -name 'endpoints.toml' \) -print0)
    done
    printf '%s' "$line_count"
}

count_endpoints() {
    awk '
        /^\[/ { section = $0 }
        section ~ /^\[(command|query|state|event|io_query)\]/ {
            if ($0 ~ /^[^#]/ && $0 !~ /^\[/) {
                count++
            }
        }
        END { print count + 0 }
    ' "$endpoints_manifest"
}

count_manifest_lines_for() {
    local endpoint_name=$1
    awk -v name="$endpoint_name" '
        $0 ~ "^[[:space:]]*" name "[[:space:]]*=" && $0 !~ /^#/ { count++ }
        END { print count + 0 }
    ' "$endpoints_manifest" | tail -1
}

count_function_lines() {
    local function_name=$1
    local file=$2
    awk -v function_name="$function_name" '
        $0 ~ "^[[:space:]]*fn " function_name "[[:space:]*(]" { capture = 1; depth = 0 }
        capture {
            for (character_index = 1; character_index <= length($0); character_index++) {
                character = substr($0, character_index, 1)
                if (character == "{") {
                    depth++
                }
                if (character == "}") {
                    depth--
                }
            }
            if ($0 !~ /^[[:space:]]*\/\// && $0 !~ /^[[:space:]]*$/) {
                count++
            }
            if (depth == 0 && $0 ~ /}/) {
                exit
            }
        }
        END { print count + 0 }
    ' "$file" | tail -1
}

count_domain_handle_body_lines() {
    awk '
        /^[[:space:]]*fn handle\(/ { capture = 1; depth = 0; next }
        capture && /^[[:space:]]*fn / { exit }
        capture {
            for (character_index = 1; character_index <= length($0); character_index++) {
                character = substr($0, character_index, 1)
                if (character == "{") {
                    depth++
                }
                if (character == "}") {
                    depth--
                }
            }
            if (depth <= 0 && $0 ~ /^[[:space:]]*\}/ ) {
                exit
            }
            if ($0 !~ /^[[:space:]]*\/\// && $0 !~ /^[[:space:]]*$/) {
                count++
            }
        }
        END { print count + 0 }
    ' "$domain_lib" | tail -1
}

count_domain_query_arm_lines() {
    local variant_name=$1
    awk -v variant="$variant_name" '
        $0 ~ "PumpQuery::" variant { capture = 1 }
        capture {
            if ($0 !~ /^[[:space:]]*\/\// && $0 !~ /^[[:space:]]*$/) {
                count++
            }
            if ($0 ~ /=>/) {
                exit
            }
        }
        END { print count + 0 }
    ' "$domain_lib" | tail -1
}

count_domain_variant_line() {
    local pattern=$1
    awk -v pattern="$pattern" '
        $0 ~ pattern && $0 !~ /^[[:space:]]*\/\// { found = 1; exit }
        END { print found + 0 }
    ' "$domain_lib" | tail -1
}

wiring_lines_for_set_level() {
    local total=0
    total=$((total + $(count_manifest_lines_for SetLevel)))
    total=$((total + $(count_domain_variant_line "SetLevel")))
    total=$((total + $(count_domain_handle_body_lines)))
    total=$((total + $(count_function_lines set_level "$api_lib")))
    printf '%s' "$total"
}

wiring_lines_for_level() {
    local total=0
    total=$((total + $(count_manifest_lines_for Level)))
    total=$((total + $(count_domain_variant_line "PumpQuery::Level")))
    total=$((total + $(count_domain_query_arm_lines Level)))
    total=$((total + $(count_function_lines level "$api_lib")))
    total=$((total + $(count_function_lines level_response "$api_lib")))
    printf '%s' "$total"
}

wiring_lines_for_pump_state() {
    local total=0
    total=$((total + $(count_manifest_lines_for pump)))
    total=$((total + $(count_function_lines pump "$api_lib")))
    printf '%s' "$total"
}

max_wiring_lines_per_endpoint() {
    local maximum=0 candidate
    for candidate in \
        "$(wiring_lines_for_set_level)" \
        "$(wiring_lines_for_level)" \
        "$(wiring_lines_for_pump_state)"; do
        if [ "$candidate" -gt "$maximum" ]; then
            maximum=$candidate
        fi
    done
    printf '%s' "$maximum"
}

count_files_for_sample_command() {
    local endpoint_name=SetLevel
    local root path count=0
    for root in "${example_minimal_roots[@]}"; do
        [ -d "$root" ] || continue
        while IFS= read -r -d '' path; do
            if is_generated "$path"; then
                continue
            fi
            if [[ ${path#"$example_dir/"} == app/tests/* ]]; then
                continue
            fi
            if grep -Fq "$endpoint_name" "$path" 2>/dev/null; then
                count=$((count + 1))
            fi
        done < <(find "$root" \( -name '*.rs' -o -name '*.toml' \) -print0)
    done
    if grep -Fq "$endpoint_name" "$endpoints_manifest" 2>/dev/null; then
        count=$((count + 1))
    fi
    printf '%s' "$count"
}

count_concepts() {
    awk '!/^#/ && !/^[[:space:]]*$/{ count++ } END { print count + 0 }' "$concepts_file"
}

framework_lines() {
    local path total=0
    for path in "${framework_read_set[@]}"; do
        if [ ! -f "$path" ]; then
            printf 'ergonomics_report: missing framework file: %s\n' "$path" >&2
            exit 1
        fi
        total=$((total + $(wc -l <"$path")))
    done
    printf '%s' "$total"
}

compare_goal() {
    local measured=$1
    local goal=$2
    if [ "$measured" -le "$goal" ]; then
        printf 'meets goal (<= %s)' "$goal"
    else
        printf 'above goal (<= %s)' "$goal"
    fi
}

require_path() {
    if [ ! -e "$1" ]; then
        printf 'ergonomics_report: missing path: %s\n' "$1" >&2
        exit 1
    fi
}

require_path "$concepts_file"
require_path "$endpoints_manifest"
require_path "$domain_lib"
require_path "$api_lib"

concepts=$(count_concepts)
wiring_per_endpoint=$(max_wiring_lines_per_endpoint)
service_lines=$(count_hand_written_service_lines)
framework=$(framework_lines)
files_per_command=$(count_files_for_sample_command)

printf '| Measure | Measured | Goal | Status |\n'
printf '| --- | ---: | ---: | --- |\n'
printf '| Concepts per Command (example-minimal) | %s | 8 or fewer | %s |\n' \
    "$concepts" "$(compare_goal "$concepts" 8)"
printf '| Wiring lines per endpoint (example-minimal) | %s | 12 or fewer | %s |\n' \
    "$wiring_per_endpoint" "$(compare_goal "$wiring_per_endpoint" 12)"
printf '| Smallest complete Service (hand-written lines) | %s | 250 or fewer | %s |\n' \
    "$service_lines" "$(compare_goal "$service_lines" 250)"
printf '| Framework lines to read first | %s | 600 or fewer | %s |\n' \
    "$framework" "$(compare_goal "$framework" 600)"
printf '| Files touched per Command (SetLevel sample) | %s | no goal yet | reported only |\n' \
    "$files_per_command"
printf '| Time to first endpoint | (not measured in CI) | 2 hours or less | documented goal only |\n'
